/* LEVENTE — THE CREATOR · tech/tree2.js — a lehetőségtér második köre: minden, amit az emberiség ismer, és ami még nem
 * Az emberi világ tükre, területenként: átkelők és infrastruktúra, közlekedés, energia, anyagok és ipar, mezőgazdaság,
 * orvoslás, kommunikáció, tudományok, társadalom és gazdaság, kultúra, hadviselés, űr, gépi elme. Semmi sincs megírva:
 * mind csak lehetőség, amelyet valakinek fel kell fedeznie — a megfelelő előzmények, anyagok, épületek és elég ember mellett.
 * Minden felfedezésnek mérhető hatása van (fx): termékenység, élettartam, biztonság, diplomácia, kereskedelem, jólét, hadierő.
 */
(function (LW) {
  'use strict';
  const D = LW.Tech.D, R = LW.Tech.RECIPES, I = LW.ITEMS, B = LW.Buildings.DEFS, Tree = LW.Tree;
  for (const k of ['fertility', 'longevity', 'safety', 'diplomacy', 'trade', 'happiness', 'war']) if (!Tree.FX_KEYS.includes(k)) Tree.FX_KEYS.push(k);

  // ---------------------------------------------------------------- tárgyak és receptek
  Object.assign(I, {
    honey: { food: 0.45, spoilDays: 2000, weight: 0.3, label: 'Méz' }, wine: { food: 0.15, water: 0.3, spoilDays: 900, weight: 0.8, label: 'Bor' }, canned_food: { food: 0.55, spoilDays: 900, weight: 0.6, label: 'Konzerv' },
    cart: { weight: 0, label: 'Szekér', tool: true, slot: 'vehicle', tier: 1 }, bicycle: { weight: 0, label: 'Kerékpár', tool: true, slot: 'vehicle', tier: 2 }, ship: { weight: 0, label: 'Hajó', tool: true, slot: 'boat', tier: 2 },
    aluminium: { weight: 1, label: 'Alumínium' }, porcelain: { weight: 0.6, label: 'Porcelán' }, fine_clothes: { weight: 1, label: 'Díszruha', tool: true, warmth: 10, slot: 'clothes', tier: 2 }, robot: { weight: 8, label: 'Robot', tool: true, slot: 'robot', tier: 1 },
  });
  I.car.tier = 3; // szekér 1, kerékpár 2, gépkocsi 3
  Object.assign(R, {
    honey: { out: { honey: 2 }, inp: { wood: 1 }, ticks: 20, tech: 'beekeeping', nearby: 'apiary', skill: 'foraging', tag: 'craft:honey' },
    wine: { out: { wine: 2 }, inp: { fruit: 4 }, ticks: 30, tech: 'viticulture', skill: 'crafting', tag: 'craft:wine' },
    canned_food: { out: { canned_food: 2 }, inpAny: [{ meat_cooked: 2, iron: 1 }, { fish_cooked: 2, iron: 1 }, { fruit: 3, glass: 1 }], ticks: 20, tech: 'canning', nearby: 'workshop', skill: 'crafting', tag: 'craft:can' },
    cart: { out: { cart: 1 }, inp: { wood: 8, fiber: 2 }, ticks: 60, tech: 'wheel', skill: 'crafting', tag: 'craft:tool' },
    bicycle: { out: { bicycle: 1 }, inp: { steel: 2, machine_part: 1 }, ticks: 40, tech: 'bicycle', nearby: 'workshop', skill: 'crafting', tag: 'craft:tool' },
    ship: { out: { ship: 1 }, inp: { wood: 20, cloth: 6, iron: 2 }, ticks: 200, tech: 'shipbuilding', nearby: 'shipyard', skill: 'building', tag: 'craft:boat' },
    aluminium: { out: { aluminium: 2 }, inp: { clay: 6, electric_part: 1 }, ticks: 40, tech: 'aluminium', nearby: 'factory', skill: 'crafting', tag: 'craft:smelt' },
    porcelain: { out: { porcelain: 2 }, inp: { clay: 6, glass: 1 }, ticks: 30, tech: 'porcelain', nearby: 'kiln', skill: 'crafting', tag: 'craft:pot' },
    fine_clothes: { out: { fine_clothes: 1 }, inp: { cloth: 3, gems: 1 }, ticks: 40, tech: 'fashion', nearby: 'workshop', skill: 'crafting', tag: 'craft:clothes' },
    robot: { out: { robot: 1 }, inp: { steel: 4, chip: 6, machine_part: 4, electric_part: 4 }, ticks: 160, tech: 'robotics', nearby: 'robot_factory', skill: 'crafting', tag: 'craft:machine' },
  });

  // ---------------------------------------------------------------- épületek
  const pub = (o) => Object.assign({ public: true }, o);
  Object.assign(B, {
    // átkelők: a hely a part, az épület a vízen/hegyben fekszik (Crossings)
    bridge: pub({ label: 'Fahíd', cost: { wood: 24, fiber: 6 }, ticks: 400, bridge: 1, span: 4, over: 'water', tech: 'bridge_building', lifeDays: 6000, minPop: 4, want: 'crossing' }),
    stone_bridge: pub({ label: 'Kőhíd', cost: { stone: 50, clay: 10 }, ticks: 900, bridge: 2, span: 8, over: 'water', tech: 'stone_bridges', lifeDays: 60000, minPop: 12, want: 'crossing' }),
    steel_bridge: pub({ label: 'Acélhíd', cost: { steel: 40, concrete: 30, machine_part: 6 }, ticks: 2400, bridge: 3, span: 20, over: 'water', tech: 'suspension_bridges', lifeDays: 80000, minPop: 28, want: 'crossing' }),
    tunnel: pub({ label: 'Alagút', cost: { steel: 20, coal: 10, concrete: 20 }, ticks: 2600, bridge: 4, span: 10, over: 'mountain', tech: 'tunneling', lifeDays: 90000, minPop: 28, want: 'crossing' }),
    // víz, út, város
    aqueduct: pub({ label: 'Vízvezeték', cost: { stone: 40, clay: 10 }, ticks: 900, water: true, irrigation: 1, tech: 'aqueducts', lifeDays: 40000, minPop: 15, want: 'water', size: [3, 1] }),
    sewer: pub({ label: 'Csatornahálózat', cost: { concrete: 24, brick: 20 }, ticks: 1200, hygiene: 1, tech: 'sewers', lifeDays: 30000, minPop: 30, want: 'health' }),
    water_tower: pub({ label: 'Víztorony', cost: { steel: 10, concrete: 16, electric_part: 4 }, ticks: 1000, water: true, hygiene: 1, tech: 'water_supply', lifeDays: 30000, minPop: 40, want: 'water' }),
    dam: pub({ label: 'Gát', cost: { concrete: 60, steel: 20, machine_part: 10 }, ticks: 3000, power: 2, irrigation: 2, tech: 'dam_building', lifeDays: 60000, minPop: 30, size: [3, 1], want: 'food' }),
    apartment_block: { label: 'Bérház', cost: { brick: 60, steel: 10, glass: 12 }, ticks: 1600, insulation: 24, safety: 0.93, sleep: 1, capacity: 16, storage: 240, dwelling: true, tier: 7, tech: 'skyscrapers', lifeDays: 30000, light: 1, size: [2, 2] },
    skyscraper: { label: 'Felhőkarcoló', cost: { steel: 60, concrete: 60, glass: 40 }, ticks: 3000, insulation: 28, safety: 0.96, sleep: 1, capacity: 30, storage: 400, dwelling: true, tier: 8, tech: 'skyscrapers', lifeDays: 40000, light: 1.4, size: [2, 2] },
    // közlekedés
    shipyard: pub({ label: 'Hajógyár', cost: { wood: 40, iron: 10, stone: 10 }, ticks: 900, workshop: 1, shipyard: true, storage: 120, harbor: 1, tech: 'shipbuilding', lifeDays: 15000, minPop: 15, size: [2, 2] }),
    rail_station: pub({ label: 'Vasútállomás', cost: { steel: 30, brick: 30, machine_part: 8 }, ticks: 1800, transport: 1, storage: 200, tech: 'rail_network', lifeDays: 30000, minPop: 35, want: 'trade', size: [2, 1] }),
    airport: pub({ label: 'Repülőtér', cost: { concrete: 80, steel: 30, glass: 10 }, ticks: 3000, transport: 2, storage: 200, tech: 'civil_aviation', lifeDays: 30000, minPop: 60, want: 'trade', size: [3, 2] }),
    // energia
    windmill: pub({ label: 'Szélmalom', cost: { wood: 30, cloth: 6, stone: 8 }, ticks: 600, mill: 1, storage: 80, tech: 'windmill', lifeDays: 12000, minPop: 15, want: 'food' }),
    hydro_plant: pub({ label: 'Vízerőmű', cost: { concrete: 60, steel: 30, electric_part: 20 }, ticks: 2800, power: 2, tech: 'hydropower', lifeDays: 40000, light: 1, minPop: 45, size: [2, 2] }),
    wind_turbine: pub({ label: 'Szélerőmű', cost: { steel: 24, electric_part: 12, concrete: 10 }, ticks: 1400, power: 1, tech: 'wind_power', lifeDays: 20000, minPop: 55 }),
    solar_farm: pub({ label: 'Naperőmű', cost: { glass: 40, chip: 8, electric_part: 16 }, ticks: 1800, power: 2, tech: 'solar_power', lifeDays: 20000, minPop: 60, size: [2, 2] }),
    nuclear_plant: pub({ label: 'Atomerőmű', cost: { concrete: 120, steel: 60, electric_part: 40 }, ticks: 5000, power: 4, tech: 'nuclear_power', lifeDays: 40000, light: 1.2, minPop: 70, size: [3, 2] }),
    fusion_plant: pub({ label: 'Fúziós erőmű', cost: { chip: 60, concrete: 80, electric_part: 60, steel: 40 }, ticks: 6000, power: 6, tech: 'fusion_power', lifeDays: 1e6, light: 1.5, minPop: 105, size: [3, 2] }),
    // ipar
    robot_factory: pub({ label: 'Robotgyár', cost: { concrete: 60, steel: 40, chip: 30, machine_part: 20 }, ticks: 3600, factory: 2, robot_factory: true, craft: 1.2, storage: 400, tech: 'robotics', lifeDays: 30000, light: 1, minPop: 75, size: [3, 2] }),
    // mezőgazdaság
    apiary: pub({ label: 'Méhes', cost: { wood: 8 }, ticks: 120, apiary: true, produce: { honey: 1 }, storage: 40, tech: 'beekeeping', lifeDays: 4000, minPop: 2, want: 'food' }),
    fish_pond: pub({ label: 'Halastó', cost: { wood: 12, stone: 8 }, ticks: 400, produce: { fish_raw: 3 }, storage: 60, tech: 'aquaculture', lifeDays: 10000, minPop: 12, want: 'food', size: [2, 1] }),
    greenhouse: pub({ label: 'Üvegház', cost: { glass: 16, wood: 12 }, ticks: 600, produce: { fruit: 4, roots: 2 }, storage: 80, tech: 'greenhouses', lifeDays: 12000, minPop: 20, want: 'food', size: [2, 1] }),
    vertical_farm: pub({ label: 'Vertikális farm', cost: { glass: 40, chip: 10, concrete: 30, electric_part: 12 }, ticks: 3000, produce: { grain: 12, fruit: 6, roots: 4 }, storage: 400, tech: 'vertical_farming', lifeDays: 30000, light: 1, minPop: 95, want: 'food', size: [2, 2] }),
    // társadalom
    courthouse: pub({ label: 'Bíróság', cost: { stone: 30, brick: 10, wood: 10 }, ticks: 800, court: 1, records: 1, tech: 'courts', lifeDays: 30000, minPop: 15, want: 'safety' }),
    assembly_hall: pub({ label: 'Népgyűlés', cost: { stone: 40, wood: 20 }, ticks: 900, assembly: 1, tech: 'democracy', lifeDays: 40000, minPop: 18, want: 'belief', size: [2, 1] }),
    police_station: pub({ label: 'Őrség', cost: { brick: 30, iron: 6, wood: 10 }, ticks: 800, police: 1, safety: 0.7, tech: 'police', lifeDays: 20000, light: 0.6, minPop: 28, want: 'safety' }),
    bank: pub({ label: 'Bank', cost: { stone: 40, brick: 20, glass: 6, coin: 20 }, ticks: 1200, bank: 1, storage: 100, tech: 'stock_market', lifeDays: 30000, minPop: 32, want: 'trade' }),
    barracks: pub({ label: 'Kaszárnya', cost: { stone: 30, wood: 20, iron: 8 }, ticks: 900, barracks: 1, safety: 0.6, storage: 80, tech: 'standing_army', lifeDays: 20000, minPop: 20, want: 'safety', size: [2, 1] }),
    // kultúra
    theatre: pub({ label: 'Színház', cost: { wood: 30, stone: 20, cloth: 10 }, ticks: 900, joy: 1, tech: 'theatre', lifeDays: 20000, light: 0.5, minPop: 15, want: 'joy', size: [2, 1] }),
    stadium: pub({ label: 'Stadion', cost: { stone: 80, brick: 20 }, ticks: 2000, joy: 2, tech: 'stadium', lifeDays: 40000, minPop: 20, want: 'joy', size: [3, 2] }),
    museum: pub({ label: 'Múzeum', cost: { stone: 40, glass: 10, paper: 10 }, ticks: 1400, joy: 1, records: 2, tech: 'museums', lifeDays: 40000, minPop: 26, want: 'knowledge', size: [2, 1] }),
    cinema: pub({ label: 'Mozi', cost: { brick: 30, electric_part: 6, cloth: 6 }, ticks: 1000, joy: 2, tech: 'cinema', lifeDays: 20000, light: 0.8, minPop: 40, want: 'joy' }),
    radio_tower: pub({ label: 'Adótorony', cost: { steel: 20, electric_part: 12, concrete: 10 }, ticks: 1200, media: 1, teach: 0.3, tech: 'television', lifeDays: 20000, light: 0.4, minPop: 50, want: 'knowledge' }),
    observatory: pub({ label: 'Csillagvizsgáló', cost: { brick: 30, glass: 12, machine_part: 2 }, ticks: 1200, lab: 1, discovery: 0.4, tech: 'observatory', lifeDays: 30000, minPop: 22, want: 'knowledge' }),
    spaceport: pub({ label: 'Űrkikötő', cost: { concrete: 120, steel: 80, chip: 30, fuel: 40 }, ticks: 5000, spaceport: 1, discovery: 0.3, tech: 'space_station', lifeDays: 40000, light: 1.2, minPop: 100, want: 'knowledge', size: [3, 3] }),
    ai_core: pub({ label: 'MI-központ', cost: { chip: 120, concrete: 40, electric_part: 40 }, ticks: 4000, computer: 3, discovery: 1, teach: 1, records: 6, tech: 'agi', lifeDays: 40000, light: 1.5, minPop: 110, want: 'knowledge', size: [2, 2] }),
  });

  // ---------------------------------------------------------------- felfedezések
  const T = (id, o) => { o.id = id; D[id] = o; };
  // — átkelők, infrastruktúra
  T('bridge_building', { name: 'Hídépítés', era: 'neolithic', prereq: ['carpentry', 'fiber_twisting'], items: { wood: 8, fiber: 4 }, difficulty: 0.86, skill: 'building', minSkill: 0.5, minPop: 4, buildings: ['bridge'], fx: { speed: 0.05 }, wow: 'Az első híd', desc: 'Gerendák a folyón át: a túlpart többé nem másik világ.' });
  T('stone_bridges', { name: 'Kőhidak', era: 'classical', prereq: ['bridge_building', 'architecture'], items: { stone: 16 }, difficulty: 0.9, skill: 'building', minSkill: 0.65, minPop: 12, buildings: ['stone_bridge'], fx: { build: 0.1, trade: 0.1 }, wow: 'Az első boltíves kőhíd', desc: 'A boltív a saját súlyával tart: a híd túléli az építőit.' });
  T('suspension_bridges', { name: 'Függőhidak', era: 'industrial', prereq: ['stone_bridges', 'steel_making', 'mechanics'], items: { steel: 8, machine_part: 2 }, difficulty: 0.95, skill: 'building', minSkill: 0.8, minPop: 28, buildings: ['steel_bridge'], fx: { trade: 0.2, speed: 0.05 }, wow: 'Híd a szigetek között', desc: 'Acélkábelen függő pálya: a tengerszoros fölött is út vezet.' });
  T('tunneling', { name: 'Alagútfúrás', era: 'industrial', prereq: ['mining', 'gunpowder', 'steel_making'], items: { steel: 4, coal: 4 }, difficulty: 0.95, skill: 'building', minSkill: 0.8, minPop: 28, buildings: ['tunnel'], fx: { mine: 0.1 }, wow: 'Az első alagút', desc: 'A hegy nem akadály, ha át lehet menni rajta.' });
  T('aqueducts', { name: 'Vízvezeték', era: 'classical', prereq: ['irrigation', 'architecture'], items: { stone: 20 }, difficulty: 0.9, skill: 'building', minSkill: 0.65, minPop: 15, buildings: ['aqueduct'], fx: { health: 0.1, farm: 0.1 }, wow: 'Az első vízvezeték', desc: 'A forrás vize a városba jön, nem a város megy a forráshoz.' });
  T('paved_roads', { name: 'Kövezett utak', era: 'classical', prereq: ['road_building', 'architecture'], items: { stone: 10 }, difficulty: 0.9, skill: 'building', minSkill: 0.6, minPop: 15, fx: { speed: 0.1, trade: 0.1 }, desc: 'Faragott kővel rakott, vízelvezetett út: télen is jár a szekér.' });
  T('canals', { name: 'Csatornázás', era: 'medieval', prereq: ['irrigation', 'stone_bridges'], items: { stone: 12 }, difficulty: 0.92, skill: 'building', minSkill: 0.7, minPop: 18, fx: { farm: 0.15, trade: 0.1 }, wow: 'Az első hajózható csatorna', desc: 'Ásott vízi út a mezők és a városok között.' });
  T('sewers', { name: 'Szennyvízcsatorna', era: 'industrial', prereq: ['sanitation', 'concrete'], items: { concrete: 8 }, difficulty: 0.94, skill: 'building', minSkill: 0.75, minPop: 30, buildings: ['sewer'], fx: { health: 0.15 }, desc: 'A szenny a föld alatt megy el: a város nem betegszik bele önmagába.' });
  T('dam_building', { name: 'Gátépítés', era: 'industrial', prereq: ['canals', 'concrete', 'mechanics'], items: { concrete: 10, steel: 4 }, difficulty: 0.95, skill: 'building', minSkill: 0.8, minPop: 30, buildings: ['dam'], fx: { farm: 0.1, safety: 0.05 }, wow: 'Az első gát', desc: 'A megfogott folyó öntöz, hajt és nem árad.' });
  T('water_supply', { name: 'Vízművek', era: 'modern', prereq: ['sewers', 'electrification'], items: { electric_part: 4, concrete: 6 }, difficulty: 0.96, skill: 'building', minSkill: 0.85, minPop: 40, buildings: ['water_tower'], fx: { health: 0.1, happiness: 0.05 }, desc: 'Csapból folyik a tiszta víz — a kút emlék lesz.' });
  T('urban_planning', { name: 'Várostervezés', era: 'modern', prereq: ['architecture', 'sanitation', 'law_code'], items: { paper: 4 }, difficulty: 0.95, skill: 'social', minSkill: 0.75, minPop: 40, fx: { build: 0.15, happiness: 0.1, health: 0.05 }, desc: 'Utcák, terek, negyedek — a város előre elgondolva.' });
  T('skyscrapers', { name: 'Felhőkarcolók', era: 'modern', prereq: ['steel_making', 'concrete', 'electrification', 'architecture'], items: { steel: 10, concrete: 10, glass: 6 }, nearby: 'factory', difficulty: 0.965, skill: 'building', minSkill: 0.85, minPop: 50, buildings: ['apartment_block', 'skyscraper'], fx: { build: 0.1 }, wow: 'Az első toronyház', desc: 'Acélváz és lift: a város fölfelé nő.' });
  // — közlekedés
  T('wheel', { name: 'Kerék', era: 'neolithic', prereq: ['woodworking', 'fiber_twisting'], items: { wood: 4 }, difficulty: 0.84, skill: 'crafting', minSkill: 0.45, recipes: ['cart'], fx: { speed: 0.05, food: 0.05 }, wow: 'Az első kerék', desc: 'Ami gurul, azt nem kell cipelni.' });
  T('horse_riding', { name: 'Lovaglás', era: 'bronze', prereq: ['animal_husbandry', 'weaving'], items: { fiber: 4, hide: 2 }, difficulty: 0.88, skill: 'hunting', minSkill: 0.5, minPop: 6, fx: { speed: 0.2, hunt: 0.1 }, wow: 'Az első lovas', desc: 'Az ember gyorsabb lett a saját lábánál.' });
  T('shipbuilding', { name: 'Hajóépítés', era: 'classical', prereq: ['sailing', 'carpentry', 'iron_working'], items: { wood: 20, cloth: 6, iron: 2 }, nearby: 'harbor', difficulty: 0.91, skill: 'building', minSkill: 0.7, minPop: 15, buildings: ['shipyard'], recipes: ['ship'], fx: { food: 0.1, trade: 0.15 }, wow: 'Az első hajó', desc: 'Bordás, szegelt test és vitorla: nyílt vízre való.' });
  T('compass', { name: 'Iránytű', era: 'medieval', prereq: ['navigation', 'iron_working'], items: { iron: 1 }, difficulty: 0.92, skill: 'crafting', minSkill: 0.7, minPop: 15, fx: { discovery: 0.05, trade: 0.1 }, desc: 'A tű mindig északra néz: a tenger többé nem útvesztő.' });
  T('steamship', { name: 'Gőzhajó', era: 'industrial', prereq: ['steam_engine', 'shipbuilding'], items: { steel: 8, machine_part: 4 }, nearby: 'shipyard', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 30, fx: { trade: 0.2, speed: 0.1 }, wow: 'Az első gőzhajó', desc: 'Szél nélkül is megy: a menetrend legyőzi az időjárást.' });
  T('rail_network', { name: 'Vasúthálózat', era: 'industrial', prereq: ['railway', 'steel_making'], items: { steel: 12 }, difficulty: 0.955, skill: 'building', minSkill: 0.8, minPop: 35, buildings: ['rail_station'], fx: { trade: 0.2 }, wow: 'Az első vasútállomás', desc: 'Állomások lánca: a városok egy testté kapcsolódnak.' });
  T('bicycle', { name: 'Kerékpár', era: 'industrial', prereq: ['machine_tools', 'wheel'], items: { steel: 2, machine_part: 1 }, nearby: 'workshop', difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 25, recipes: ['bicycle'], fx: { speed: 0.05, health: 0.05 }, desc: 'Két kerék és egy lánc: mindenki gyorsabb lesz.' });
  T('civil_aviation', { name: 'Polgári repülés', era: 'modern', prereq: ['aviation', 'rail_network'], items: { steel: 10, fuel: 4 }, nearby: 'factory', difficulty: 0.97, skill: 'crafting', minSkill: 0.88, minPop: 60, buildings: ['airport'], fx: { trade: 0.3, speed: 0.2 }, wow: 'Az első repülőtér', desc: 'Menetrend szerint az égen: a világ egy napra zsugorodik.' });
  T('container_shipping', { name: 'Konténerhajózás', era: 'digital', prereq: ['steamship', 'computer'], items: { steel: 20, machine_part: 6 }, nearby: 'shipyard', difficulty: 0.975, skill: 'building', minSkill: 0.88, minPop: 70, fx: { trade: 0.3, food: 0.1 }, desc: 'Egyforma dobozok: a rakodás ideje elolvad.' });
  T('electric_vehicles', { name: 'Elektromos járművek', era: 'digital', prereq: ['automobile', 'battery', 'electrification'], items: { electric_part: 8, chip: 4 }, nearby: 'factory', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 80, fx: { speed: 0.1, health: 0.05 }, desc: 'Csendes, füst nélküli kerekek.' });
  T('autonomous_vehicles', { name: 'Önvezető járművek', era: 'ai', prereq: ['electric_vehicles', 'machine_learning'], items: { chip: 12 }, nearby: 'data_center', difficulty: 0.985, skill: 'crafting', minSkill: 0.92, minPop: 100, fx: { speed: 0.2, trade: 0.2, safety: 0.1 }, wow: 'Az első gép, amely magától hazatalál', desc: 'A jármű lát, dönt és nem fárad el.' });
  // — energia
  T('watermill', { name: 'Vízimalom', era: 'classical', prereq: ['milling', 'mechanics'], items: { wood: 12, stone: 6 }, difficulty: 0.9, skill: 'building', minSkill: 0.65, minPop: 12, fx: { craft: 0.1, farm: 0.1 }, desc: 'A folyó forgatja a követ: a munka egy része a vízé lesz.' });
  T('windmill', { name: 'Szélmalom', era: 'medieval', prereq: ['watermill', 'carpentry'], items: { wood: 16, cloth: 4 }, difficulty: 0.92, skill: 'building', minSkill: 0.7, minPop: 15, buildings: ['windmill'], fx: { craft: 0.1, food: 0.05 }, wow: 'Az első szélmalom', desc: 'Ahol nincs folyó, ott a szél dolgozik.' });
  T('coal_power', { name: 'Széntüzelés', era: 'industrial', prereq: ['steam_engine', 'ore_lore_coal'], items: { coal: 8 }, difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 25, fx: { warmth: 2, craft: 0.15 }, desc: 'A föld fekete köve fűt és hajt — és füstöt hagy maga után.' });
  T('battery', { name: 'Akkumulátor', era: 'industrial', prereq: ['electricity', 'chemistry'], items: { copper: 2, glass: 1 }, nearby: 'lab', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 30, fx: { craft: 0.05, discovery: 0.05 }, desc: 'Tárolt villám: az áram elvihető.' });
  T('power_grid', { name: 'Villamos hálózat', era: 'modern', prereq: ['electrification', 'battery'], items: { copper: 10, electric_part: 6 }, difficulty: 0.96, skill: 'building', minSkill: 0.85, minPop: 45, fx: { craft: 0.15, warmth: 1 }, desc: 'Vezetékek hálója a városok fölött: egy erőmű mindenkié.' });
  T('hydropower', { name: 'Vízerőmű', era: 'modern', prereq: ['dam_building', 'electrification'], items: { steel: 10, electric_part: 8 }, difficulty: 0.965, skill: 'building', minSkill: 0.85, minPop: 45, buildings: ['hydro_plant'], fx: { craft: 0.2 }, wow: 'Az első vízerőmű', desc: 'A zuhanó víz fényt csinál.' });
  T('wind_power', { name: 'Szélerőmű', era: 'digital', prereq: ['windmill', 'electrification', 'machine_tools'], items: { steel: 12, electric_part: 8 }, difficulty: 0.97, skill: 'building', minSkill: 0.85, minPop: 55, buildings: ['wind_turbine'], fx: { craft: 0.1, health: 0.05 }, desc: 'A régi szélmalom unokája áramot terem.' });
  T('solar_power', { name: 'Napenergia', era: 'digital', prereq: ['transistor', 'glassmaking'], items: { glass: 10, chip: 4, electric_part: 6 }, nearby: 'lab', difficulty: 0.975, skill: 'crafting', minSkill: 0.88, minPop: 60, buildings: ['solar_farm'], fx: { craft: 0.2, health: 0.05 }, wow: 'Az első napelem', desc: 'A fény maga lesz az erő.' });
  T('nuclear_power', { name: 'Atomerőmű', era: 'digital', prereq: ['nuclear_fission', 'concrete'], items: { concrete: 30, steel: 20, electric_part: 20 }, nearby: 'lab', difficulty: 0.975, skill: 'building', minSkill: 0.9, minPop: 70, buildings: ['nuclear_plant'], fx: { craft: 0.4, discovery: 0.1 }, wow: 'Az első atomerőmű', desc: 'Az atommag szelíd tüze: rengeteg erő, kevés füst, nagy felelősség.' });
  T('fusion_power', { name: 'Fúziós erőmű', era: 'ai', prereq: ['fusion'], items: { chip: 60, concrete: 40, electric_part: 40 }, nearby: 'data_center', difficulty: 0.988, skill: 'building', minSkill: 0.93, minPop: 105, buildings: ['fusion_plant'], fx: { craft: 0.6, warmth: 4 }, wow: 'A csillagok tüze a földön', desc: 'Ami a napban ég, most a városban ég.' });
  // — anyagok, ipar
  T('porcelain', { name: 'Porcelán', era: 'medieval', prereq: ['pottery', 'kiln_building', 'glassmaking'], items: { clay: 8, glass: 1 }, nearby: 'kiln', difficulty: 0.92, skill: 'crafting', minSkill: 0.7, minPop: 15, recipes: ['porcelain'], fx: { trade: 0.1, happiness: 0.05 }, desc: 'Fehér, csengő, áttetsző agyag: a kereskedők kincse.' });
  T('metallurgy', { name: 'Fémötvözetek', era: 'renaissance', prereq: ['steel_making', 'chemistry'], items: { steel: 4, copper: 2 }, nearby: 'forge', difficulty: 0.94, skill: 'crafting', minSkill: 0.8, minPop: 24, fx: { craft: 0.15, mine: 0.1 }, desc: 'Ami két fémből lesz, erősebb mindkettőnél.' });
  T('canning', { name: 'Konzerválás', era: 'industrial', prereq: ['steel_making', 'glassmaking', 'food_drying'], items: { iron: 2, glass: 2 }, nearby: 'workshop', difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 25, recipes: ['canned_food'], fx: { preserve: 0.3 }, desc: 'Lezárt, forralt étel, amely évekig eláll.' });
  T('aluminium', { name: 'Alumínium', era: 'modern', prereq: ['electrification', 'chemistry'], items: { electric_part: 4, clay: 6 }, nearby: 'factory', difficulty: 0.96, skill: 'crafting', minSkill: 0.85, minPop: 40, recipes: ['aluminium'], fx: { craft: 0.1, speed: 0.05 }, desc: 'Könnyű fém az agyagból — árammal.' });
  T('synthetic_fibers', { name: 'Műszálak', era: 'modern', prereq: ['plastics', 'weaving'], items: { plastic: 4 }, nearby: 'factory', difficulty: 0.96, skill: 'crafting', minSkill: 0.82, minPop: 40, fx: { warmth: 2, craft: 0.05 }, desc: 'Olajból szőtt kelme: olcsó, meleg, nem rohad.' });
  T('assembly_line', { name: 'Futószalag', era: 'modern', prereq: ['factory_system', 'automobile'], items: { machine_part: 8 }, nearby: 'factory', difficulty: 0.965, skill: 'crafting', minSkill: 0.85, minPop: 45, fx: { craft: 0.4, build: 0.1 }, wow: 'Az első futószalag', desc: 'Nem a munkás megy a munkához: a munka megy a munkáshoz.' });
  T('recycling', { name: 'Újrahasznosítás', era: 'digital', prereq: ['plastics', 'sanitation'], items: { plastic: 4 }, difficulty: 0.97, skill: 'crafting', minSkill: 0.8, minPop: 50, fx: { craft: 0.1, preserve: 0.1, health: 0.05 }, desc: 'A szemét nyersanyag lesz.' });
  T('additive_manufacturing', { name: 'Additív gyártás', era: 'digital', prereq: ['computer', 'plastics', 'machine_tools'], items: { plastic: 6, chip: 4 }, nearby: 'factory', difficulty: 0.975, skill: 'crafting', minSkill: 0.88, minPop: 60, fx: { craft: 0.25, build: 0.2 }, desc: 'A gép rétegről rétegre nyomtatja a tárgyat.' });
  T('robotics', { name: 'Robotika', era: 'digital', prereq: ['computer', 'machine_tools', 'assembly_line'], items: { chip: 12, machine_part: 8 }, nearby: 'factory', difficulty: 0.978, skill: 'crafting', minSkill: 0.9, minPop: 75, buildings: ['robot_factory'], recipes: ['robot'], fx: { craft: 0.6, build: 0.3, farm: 0.2 }, wow: 'Az első robot', desc: 'Egy gép, amely dolgozik, nem fárad, és nem kér semmit.' });
  T('automation', { name: 'Automatizálás', era: 'digital', prereq: ['software', 'robotics'], items: { chip: 8 }, nearby: 'robot_factory', difficulty: 0.978, skill: 'crafting', minSkill: 0.9, minPop: 75, fx: { craft: 0.3, farm: 0.2, build: 0.2 }, desc: 'A gyár magától jár: az ember csak nézi.' });
  T('nanotech', { name: 'Nanotechnológia', era: 'ai', prereq: ['robotics', 'chemistry', 'genetics'], items: { chip: 20, medicine: 4 }, nearby: 'lab', difficulty: 0.985, skill: 'crafting', minSkill: 0.93, minPop: 95, fx: { craft: 0.3, health: 0.2, longevity: 4 }, wow: 'Gépek, amelyeket nem látni', desc: 'Az anyag atomonként rendezve.' });
  // — mezőgazdaság, élelem
  T('beekeeping', { name: 'Méhészet', era: 'neolithic', prereq: ['horticulture'], items: { wood: 4 }, difficulty: 0.84, skill: 'foraging', minSkill: 0.45, minPop: 2, buildings: ['apiary'], recipes: ['honey'], fx: { food: 0.05 }, wow: 'Az első méz', desc: 'A méhek dolgoznak, az ember gyűjt.' });
  T('salting', { name: 'Sózás', era: 'neolithic', prereq: ['food_drying'], items: { salt: 2 }, difficulty: 0.83, skill: 'crafting', minSkill: 0.35, fx: { preserve: 0.2 }, desc: 'Sóban a hús nem romlik meg.' });
  T('viticulture', { name: 'Szőlőművelés', era: 'bronze', prereq: ['horticulture', 'brewing'], items: { fruit: 6 }, difficulty: 0.88, skill: 'farming', minSkill: 0.55, minPop: 6, recipes: ['wine'], fx: { happiness: 0.1 }, wow: 'Az első bor', desc: 'A megerjedt gyümölcs öröm és ünnep.' });
  T('terrace_farming', { name: 'Teraszos művelés', era: 'bronze', prereq: ['plowing', 'stone_masonry'], items: { stone: 8 }, difficulty: 0.88, skill: 'farming', minSkill: 0.55, minPop: 8, fx: { farm: 0.15 }, desc: 'A domboldal lépcsőin is terem a föld.' });
  T('aquaculture', { name: 'Haltenyésztés', era: 'classical', prereq: ['fishing', 'irrigation'], items: { wood: 8 }, difficulty: 0.9, skill: 'farming', minSkill: 0.6, minPop: 12, buildings: ['fish_pond'], fx: { food: 0.1 }, desc: 'A hal nem a tengerből jön: tóban nevelik.' });
  T('selective_breeding', { name: 'Nemesítés', era: 'medieval', prereq: ['animal_husbandry', 'crop_rotation'], items: { grain: 8 }, difficulty: 0.92, skill: 'farming', minSkill: 0.7, minPop: 15, fx: { farm: 0.2, food: 0.1 }, desc: 'A legjobb magból vetnek, a legjobb állatot hagyják szaporodni.' });
  T('greenhouses', { name: 'Üvegház', era: 'renaissance', prereq: ['glassmaking', 'horticulture'], items: { glass: 8, wood: 8 }, difficulty: 0.94, skill: 'building', minSkill: 0.75, minPop: 20, buildings: ['greenhouse'], fx: { food: 0.05 }, wow: 'Az első üvegház', desc: 'Üveg alatt télen is nyár van.' });
  T('fertilizers', { name: 'Műtrágya', era: 'industrial', prereq: ['chemistry', 'crop_rotation'], items: { coal: 2, salt: 2 }, nearby: 'lab', difficulty: 0.945, skill: 'farming', minSkill: 0.78, minPop: 28, fx: { farm: 0.35, fertility: 0.05 }, wow: 'Kenyér a levegőből', desc: 'A föld tápláléka gyárból jön: a termés megkétszereződik.' });
  T('mechanized_farming', { name: 'Gépesített mezőgazdaság', era: 'modern', prereq: ['internal_combustion', 'plowing'], items: { steel: 6, machine_part: 4 }, nearby: 'factory', difficulty: 0.96, skill: 'farming', minSkill: 0.82, minPop: 40, fx: { farm: 0.4, food: 0.15 }, desc: 'Egy ember egy géppel száz ember munkáját végzi a földeken.' });
  T('refrigeration', { name: 'Hűtés', era: 'modern', prereq: ['electrification', 'chemistry'], items: { electric_part: 4, copper: 2 }, nearby: 'factory', difficulty: 0.96, skill: 'crafting', minSkill: 0.82, minPop: 40, fx: { preserve: 0.5, health: 0.1 }, wow: 'Az első hűtőszekrény', desc: 'A hideg megáll a dobozban: a nyár is eltartja az ételt.' });
  T('gmo', { name: 'Génmódosított növények', era: 'ai', prereq: ['genetics', 'fertilizers'], items: { medicine: 2, chip: 2 }, nearby: 'lab', difficulty: 0.98, skill: 'medicine', minSkill: 0.9, minPop: 80, fx: { farm: 0.4, food: 0.1 }, desc: 'A növény kódját átírják: több terem, kevesebb vész el.' });
  T('vertical_farming', { name: 'Vertikális farm', era: 'ai', prereq: ['gmo', 'solar_power', 'robotics'], items: { chip: 10, glass: 10 }, nearby: 'robot_factory', difficulty: 0.985, skill: 'building', minSkill: 0.92, minPop: 95, buildings: ['vertical_farm'], fx: { food: 0.3 }, wow: 'Mező a toronyban', desc: 'Emeletes földek fény alatt: a város eteti önmagát.' });
  // — orvoslás, egészség
  T('surgery', { name: 'Sebészet', era: 'classical', prereq: ['medicine', 'bronze_tools'], items: { bronze: 1, cloth: 2 }, difficulty: 0.9, skill: 'medicine', minSkill: 0.65, minPop: 12, fx: { health: 0.15 }, wow: 'Az első műtét', desc: 'Kés a gyógyítás szolgálatában.' });
  T('quarantine', { name: 'Vesztegzár', era: 'medieval', prereq: ['medicine', 'law_code'], items: { paper: 1 }, difficulty: 0.92, skill: 'social', minSkill: 0.65, minPop: 18, fx: { health: 0.2 }, desc: 'A beteget elkülönítik: a kór nem jut tovább.' });
  T('germ_theory', { name: 'Kórokozó-elmélet', era: 'industrial', prereq: ['optics', 'scientific_method', 'medicine'], items: { glass: 4 }, nearby: 'lab', difficulty: 0.945, skill: 'medicine', minSkill: 0.78, minPop: 25, fx: { health: 0.3 }, wow: 'A láthatatlan ellenség felfedezése', desc: 'A betegséget apró élőlények hozzák — és a tisztaság megállítja őket.' });
  T('anesthesia', { name: 'Érzéstelenítés', era: 'industrial', prereq: ['chemistry', 'surgery'], items: { medicine: 2 }, nearby: 'lab', difficulty: 0.945, skill: 'medicine', minSkill: 0.78, minPop: 25, fx: { health: 0.15, longevity: 2 }, desc: 'A műtét többé nem kín.' });
  T('antibiotics', { name: 'Antibiotikum', era: 'modern', prereq: ['germ_theory', 'pharmacology'], items: { medicine: 4, glass: 2 }, nearby: 'lab', difficulty: 0.96, skill: 'medicine', minSkill: 0.85, minPop: 40, fx: { health: 0.4, longevity: 5 }, wow: 'Az első antibiotikum', desc: 'Penészből nyert csoda: a fertőzés meggyógyítható.' });
  T('psychology', { name: 'Lélektan', era: 'modern', prereq: ['anatomy', 'universities', 'printing'], items: { book: 2 }, nearby: 'university', difficulty: 0.955, skill: 'social', minSkill: 0.8, minPop: 35, fx: { happiness: 0.2, teach: 0.1 }, desc: 'A lélek is vizsgálható, gyógyítható.' });
  T('public_health', { name: 'Népegészségügy', era: 'modern', prereq: ['modern_medicine', 'law_code'], items: { medicine: 4 }, nearby: 'hospital', difficulty: 0.96, skill: 'medicine', minSkill: 0.82, minPop: 45, fx: { health: 0.2, longevity: 4, fertility: 0.05 }, desc: 'Oltás mindenkinek, orvos minden faluban.' });
  T('family_planning', { name: 'Családtervezés', era: 'modern', prereq: ['public_health', 'psychology'], items: { medicine: 2 }, difficulty: 0.96, skill: 'social', minSkill: 0.8, minPop: 45, fx: { fertility: -0.2, happiness: 0.05, teach: 0.05 }, desc: 'Kevesebb gyerek születik, és mind felnő.' });
  T('medical_imaging', { name: 'Képalkotó diagnosztika', era: 'digital', prereq: ['electricity', 'computer', 'anatomy'], items: { electric_part: 6, chip: 4 }, nearby: 'hospital', difficulty: 0.975, skill: 'medicine', minSkill: 0.88, minPop: 60, fx: { health: 0.2, longevity: 3 }, desc: 'Belelátni a testbe, mielőtt felnyitnák.' });
  T('organ_transplant', { name: 'Szervátültetés', era: 'digital', prereq: ['surgery', 'antibiotics', 'modern_medicine'], items: { medicine: 8 }, nearby: 'hospital', difficulty: 0.975, skill: 'medicine', minSkill: 0.9, minPop: 65, fx: { longevity: 4 }, wow: 'Egy szív, amely tovább dobog', desc: 'Ami elromlott, kicserélhető.' });
  T('neuroscience', { name: 'Idegtudomány', era: 'digital', prereq: ['psychology', 'medical_imaging'], items: { chip: 4, medicine: 4 }, nearby: 'lab', difficulty: 0.978, skill: 'medicine', minSkill: 0.9, minPop: 70, fx: { teach: 0.2, health: 0.1, happiness: 0.1 }, desc: 'Az agy térképe: hol lakik a gondolat.' });
  T('gene_therapy', { name: 'Génterápia', era: 'ai', prereq: ['genetics', 'machine_learning'], items: { medicine: 8, chip: 8 }, nearby: 'hospital', difficulty: 0.985, skill: 'medicine', minSkill: 0.93, minPop: 95, fx: { health: 0.3, longevity: 8 }, wow: 'A betegség átírása', desc: 'A hibát nem kezelik: kijavítják a kódban.' });
  T('life_extension', { name: 'Élethosszabbítás', era: 'ai', prereq: ['gene_therapy', 'nanotech'], items: { medicine: 12, chip: 12 }, nearby: 'hospital', difficulty: 0.988, skill: 'medicine', minSkill: 0.95, minPop: 105, fx: { longevity: 15 }, wow: 'A halál elhalasztása', desc: 'Az öregedés is csak betegség — és gyógyítják.' });
  // — kommunikáció, információ
  T('postal_service', { name: 'Postaszolgálat', era: 'classical', prereq: ['road_building', 'alphabet'], items: { fiber: 2, wood: 2 }, difficulty: 0.9, skill: 'social', minSkill: 0.6, minPop: 15, fx: { teach: 0.1, trade: 0.1, diplomacy: 0.1 }, desc: 'Futárok láncán az üzenet gyorsabb a hírnél.' });
  T('newspaper', { name: 'Újság', era: 'renaissance', prereq: ['printing'], items: { paper: 6 }, nearby: 'printing_house', difficulty: 0.94, skill: 'social', minSkill: 0.75, minPop: 24, fx: { teach: 0.15, diplomacy: 0.05 }, wow: 'Az első újság', desc: 'Mindenki ugyanazt tudja meg ugyanazon a reggelen.' });
  T('photography', { name: 'Fényképezés', era: 'industrial', prereq: ['optics', 'chemistry'], items: { glass: 2, salt: 1 }, nearby: 'lab', difficulty: 0.945, skill: 'crafting', minSkill: 0.75, minPop: 25, fx: { happiness: 0.05, teach: 0.05 }, wow: 'Az első fénykép', desc: 'A fény maga rajzol: az arc megmarad.' });
  T('telephone', { name: 'Telefon', era: 'industrial', prereq: ['telegraph', 'electricity'], items: { copper: 4, electric_part: 2 }, nearby: 'workshop', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 32, fx: { teach: 0.1, trade: 0.15, diplomacy: 0.1 }, wow: 'Az első telefonhívás', desc: 'A hang átmegy a dróton.' });
  T('cinema', { name: 'Mozgókép', era: 'modern', prereq: ['photography', 'electrification'], items: { electric_part: 2, glass: 2 }, difficulty: 0.96, skill: 'crafting', minSkill: 0.82, minPop: 40, buildings: ['cinema'], fx: { happiness: 0.15 }, wow: 'Az első film', desc: 'A képek megmozdulnak a vásznon.' });
  T('television', { name: 'Televízió', era: 'modern', prereq: ['radio', 'cinema'], items: { electric_part: 6 }, nearby: 'factory', difficulty: 0.965, skill: 'crafting', minSkill: 0.85, minPop: 50, buildings: ['radio_tower'], fx: { teach: 0.2, happiness: 0.1 }, wow: 'Az első adás', desc: 'Kép és hang minden házban egyszerre.' });
  T('cryptography', { name: 'Titkosítás', era: 'digital', prereq: ['mathematics', 'computer'], items: { chip: 2 }, nearby: 'computer_center', difficulty: 0.97, skill: 'crafting', minSkill: 0.85, minPop: 55, fx: { safety: 0.1, trade: 0.1 }, desc: 'Amit csak a címzett olvashat.' });
  T('mobile_phone', { name: 'Mobiltelefon', era: 'digital', prereq: ['telephone', 'integrated_circuit', 'radio'], items: { chip: 4, plastic: 2 }, nearby: 'factory', difficulty: 0.975, skill: 'crafting', minSkill: 0.88, minPop: 65, fx: { teach: 0.15, trade: 0.15, happiness: 0.05 }, wow: 'Telefon a zsebben', desc: 'Mindenki mindenkivel, bárhol.' });
  T('satellites', { name: 'Műholdak', era: 'digital', prereq: ['spaceflight', 'radio'], items: { chip: 10, steel: 10 }, nearby: 'computer_center', difficulty: 0.98, skill: 'crafting', minSkill: 0.92, minPop: 90, fx: { discovery: 0.2, teach: 0.1 }, wow: 'Az első műhold', desc: 'Egy szem az égben: az egész világ egyetlen térképen.' });
  T('social_networks', { name: 'Közösségi hálók', era: 'ai', prereq: ['internet', 'mobile_phone'], items: { chip: 6 }, nearby: 'data_center', difficulty: 0.98, skill: 'social', minSkill: 0.85, minPop: 80, fx: { teach: 0.1, happiness: -0.05, diplomacy: -0.05 }, desc: 'Mindenki beszél mindenkihez — és hangosabb lesz a világ.' });
  T('quantum_computing', { name: 'Kvantumszámítás', era: 'ai', prereq: ['integrated_circuit', 'cryptography', 'quantum_mechanics'], items: { chip: 40 }, nearby: 'data_center', difficulty: 0.987, skill: 'crafting', minSkill: 0.95, minPop: 105, fx: { discovery: 0.4 }, wow: 'Az első kvantumszámítógép', desc: 'Egyszerre minden út: a megoldás egy pillanat.' });
  // — tudományok
  T('geometry', { name: 'Mértan', era: 'classical', prereq: ['mathematics'], items: { clay: 2 }, difficulty: 0.9, skill: 'crafting', minSkill: 0.6, minPop: 12, fx: { build: 0.15, discovery: 0.05 }, desc: 'A világ vonalakból és szögekből leírható.' });
  T('philosophy', { name: 'Filozófia', era: 'classical', prereq: ['schooling', 'alphabet'], items: {}, nearby: 'school', difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, fx: { teach: 0.15, happiness: 0.05, discovery: 0.05 }, wow: 'Az első filozófus', desc: 'Kérdezni kezdenek, hogy miért.' });
  T('theology', { name: 'Teológia', era: 'classical', prereq: ['organized_religion', 'alphabet'], items: { clay: 4 }, nearby: 'temple', difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, fx: { happiness: 0.1, teach: 0.05 }, desc: 'A hang az égből tanná rendeződik.' });
  T('physics', { name: 'Fizika', era: 'renaissance', prereq: ['scientific_method', 'mechanics', 'mathematics'], items: { glass: 2, iron: 2 }, nearby: 'university', difficulty: 0.945, skill: 'crafting', minSkill: 0.8, minPop: 24, fx: { discovery: 0.2 }, desc: 'Az esés és a bolygók egyazon törvény alatt.' });
  T('biology', { name: 'Biológia', era: 'renaissance', prereq: ['anatomy', 'optics'], items: { glass: 2 }, nearby: 'university', difficulty: 0.94, skill: 'medicine', minSkill: 0.78, minPop: 22, fx: { health: 0.1, farm: 0.1, discovery: 0.1 }, desc: 'Az élet rendszerezve: fajok, sejtek, rokonságok.' });
  T('geology', { name: 'Földtan', era: 'renaissance', prereq: ['mining', 'scientific_method'], items: { stone: 6, ore_iron: 2 }, difficulty: 0.94, skill: 'crafting', minSkill: 0.78, minPop: 22, fx: { mine: 0.3, discovery: 0.05 }, desc: 'A rétegek elmesélik, hol van az érc.' });
  T('economics', { name: 'Közgazdaságtan', era: 'renaissance', prereq: ['banking', 'printing'], items: { book: 1 }, nearby: 'university', difficulty: 0.945, skill: 'social', minSkill: 0.8, minPop: 26, fx: { trade: 0.25 }, desc: 'A piac láthatatlan keze leírva.' });
  T('statistics', { name: 'Statisztika', era: 'industrial', prereq: ['mathematics', 'printing'], items: { paper: 4 }, nearby: 'university', difficulty: 0.945, skill: 'social', minSkill: 0.78, minPop: 28, fx: { discovery: 0.1, health: 0.05, teach: 0.05 }, desc: 'A sokaság szabályai: a véletlen is mérhető.' });
  T('evolution', { name: 'Evolúcióelmélet', era: 'industrial', prereq: ['biology', 'geology'], items: { book: 2 }, nearby: 'university', difficulty: 0.955, skill: 'medicine', minSkill: 0.8, minPop: 30, fx: { discovery: 0.15, farm: 0.05 }, wow: 'Az élet fája', desc: 'Az élők nem készen születtek: változtak, és változnak.' });
  T('relativity', { name: 'Relativitás', era: 'modern', prereq: ['physics', 'mathematics', 'astronomy'], items: { paper: 4 }, nearby: 'university', difficulty: 0.965, skill: 'crafting', minSkill: 0.88, minPop: 45, fx: { discovery: 0.2 }, desc: 'Az idő és a tér egymásba hajlik.' });
  T('quantum_mechanics', { name: 'Kvantummechanika', era: 'modern', prereq: ['relativity', 'chemistry'], items: { glass: 4, electric_part: 2 }, nearby: 'lab', difficulty: 0.97, skill: 'crafting', minSkill: 0.9, minPop: 50, fx: { discovery: 0.25 }, desc: 'A legkisebb dolgok nem úgy viselkednek, ahogy a nagyok.' });
  T('climate_science', { name: 'Klímatudomány', era: 'digital', prereq: ['statistics', 'chemistry', 'computer'], items: { chip: 4 }, nearby: 'computer_center', difficulty: 0.975, skill: 'crafting', minSkill: 0.88, minPop: 65, fx: { farm: 0.1, preserve: 0.1, safety: 0.05 }, desc: 'Az égbolt mintái évtizedekre előre.' });
  T('unified_theory', { name: 'Egyesített elmélet', era: 'ai', prereq: ['quantum_mechanics', 'relativity', 'quantum_computing'], items: { chip: 20 }, nearby: 'data_center', difficulty: 0.988, skill: 'crafting', minSkill: 0.95, minPop: 105, fx: { discovery: 0.5 }, wow: 'A mindenség képlete', desc: 'Egy egyenlet, amely mindent leír — kivéve, hogy miért.' });
  // — társadalom, politika, gazdaság
  T('bureaucracy', { name: 'Hivatalnokrend', era: 'classical', prereq: ['law_code', 'alphabet', 'counting'], items: { clay: 4 }, nearby: 'archive', difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 18, fx: { trade: 0.1, build: 0.1, diplomacy: 0.05 }, desc: 'Írnokok, adók, nyilvántartás: az állam emlékezete.' });
  T('taxation', { name: 'Adózás', era: 'classical', prereq: ['counting', 'bureaucracy'], items: { coin: 4 }, difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, fx: { build: 0.2 }, desc: 'Mindenki ad egy keveset, hogy legyen közös.' });
  T('courts', { name: 'Bíróság', era: 'classical', prereq: ['law_code', 'bureaucracy'], items: {}, nearby: 'archive', difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, buildings: ['courthouse'], fx: { safety: 0.15 }, wow: 'Az első ítélet', desc: 'A vitát nem az erősebb dönti el.' });
  T('diplomacy', { name: 'Diplomácia', era: 'classical', prereq: ['law_code', 'writing'], items: { clay: 2 }, difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, fx: { diplomacy: 0.3 }, wow: 'Az első békeszerződés', desc: 'Követek járnak a városok között, nem hadak.' });
  T('democracy', { name: 'Népuralom', era: 'classical', prereq: ['philosophy', 'law_code'], items: {}, nearby: 'school', difficulty: 0.91, skill: 'social', minSkill: 0.7, minPop: 18, buildings: ['assembly_hall'], fx: { happiness: 0.1, diplomacy: 0.1 }, wow: 'Az első választás', desc: 'A vezetőt választják, és le is válthatják.' });
  T('guilds', { name: 'Céhek', era: 'medieval', prereq: ['trade', 'carpentry', 'law_code'], items: {}, nearby: 'workshop', difficulty: 0.92, skill: 'social', minSkill: 0.7, minPop: 18, fx: { craft: 0.15, teach: 0.1 }, desc: 'A mesterek közössége: tudás, mérce, védelem.' });
  T('constitution', { name: 'Alkotmány', era: 'renaissance', prereq: ['democracy', 'printing'], items: { paper: 4 }, nearby: 'assembly_hall', difficulty: 0.945, skill: 'social', minSkill: 0.8, minPop: 26, fx: { safety: 0.1, happiness: 0.1, diplomacy: 0.1 }, desc: 'Leírt szabály, amely a hatalom fölött áll.' });
  T('insurance', { name: 'Biztosítás', era: 'renaissance', prereq: ['banking', 'economics'], items: { coin: 6 }, difficulty: 0.945, skill: 'social', minSkill: 0.8, minPop: 26, fx: { safety: 0.1, trade: 0.1, preserve: 0.1 }, desc: 'A közösen viselt kockázat kisebb.' });
  T('police', { name: 'Rendfenntartás', era: 'industrial', prereq: ['law_code', 'bureaucracy'], items: { iron: 2 }, nearby: 'courthouse', difficulty: 0.94, skill: 'social', minSkill: 0.75, minPop: 28, buildings: ['police_station'], fx: { safety: 0.3 }, desc: 'Őrség a városnak, nem a fejedelemnek.' });
  T('stock_market', { name: 'Tőzsde', era: 'industrial', prereq: ['banking', 'economics', 'newspaper'], items: { coin: 10, paper: 4 }, difficulty: 0.95, skill: 'social', minSkill: 0.82, minPop: 32, buildings: ['bank'], fx: { trade: 0.3 }, wow: 'Az első tőzsde', desc: 'A vállalat darabokra osztva bárkié lehet.' });
  T('universal_education', { name: 'Általános tankötelezettség', era: 'industrial', prereq: ['schooling', 'printing', 'law_code'], items: { book: 4 }, nearby: 'school', difficulty: 0.95, skill: 'social', minSkill: 0.8, minPop: 32, fx: { teach: 0.4 }, wow: 'Mindenki iskolába jár', desc: 'Nem a szülő dönti el, ki tanul: mindenki.' });
  T('labor_unions', { name: 'Szakszervezet', era: 'industrial', prereq: ['factory_system', 'printing'], items: { paper: 2 }, nearby: 'factory', difficulty: 0.945, skill: 'social', minSkill: 0.75, minPop: 30, fx: { happiness: 0.15, safety: 0.05 }, desc: 'A munkások együtt erősebbek a gyárnál.' });
  T('welfare_state', { name: 'Jóléti állam', era: 'modern', prereq: ['public_health', 'democracy', 'stock_market'], items: { coin: 10 }, nearby: 'assembly_hall', difficulty: 0.96, skill: 'social', minSkill: 0.85, minPop: 50, fx: { happiness: 0.2, health: 0.1, fertility: 0.05 }, wow: 'Senki sem marad éhen', desc: 'A közösség tartja el azt, aki elesett.' });
  T('international_law', { name: 'Nemzetközi jog', era: 'modern', prereq: ['diplomacy', 'constitution'], items: { paper: 6 }, nearby: 'assembly_hall', difficulty: 0.96, skill: 'social', minSkill: 0.85, minPop: 45, fx: { diplomacy: 0.3 }, desc: 'Szabály a városok fölött is.' });
  // — kultúra, művészet, sport
  T('music', { name: 'Zene', era: 'neolithic', prereq: ['ritual'], items: { wood: 2, fiber: 2 }, difficulty: 0.8, skill: 'social', minSkill: 0.35, fx: { happiness: 0.15 }, wow: 'Az első dal', desc: 'Ritmus és dallam: együtt könnyebb az este.' });
  T('painting', { name: 'Festészet', era: 'neolithic', prereq: ['ritual', 'clay_awareness'], items: { clay: 2, berries: 2 }, difficulty: 0.82, skill: 'crafting', minSkill: 0.4, fx: { happiness: 0.1, teach: 0.05 }, wow: 'Az első barlangrajz', desc: 'A falra festett vad emlékezik a vadászra.' });
  T('sports', { name: 'Versenyjátékok', era: 'neolithic', prereq: ['ritual', 'spear_making'], items: {}, difficulty: 0.82, skill: 'social', minSkill: 0.4, minPop: 6, fx: { happiness: 0.1, health: 0.05 }, wow: 'Az első verseny', desc: 'Ki fut gyorsabban, ki dob messzebb: a játék is összetart.' });
  T('sculpture', { name: 'Szobrászat', era: 'bronze', prereq: ['stone_masonry', 'painting'], items: { stone: 6 }, difficulty: 0.88, skill: 'crafting', minSkill: 0.55, minPop: 8, fx: { happiness: 0.1 }, desc: 'A kőből ember lép elő.' });
  T('theatre', { name: 'Színház', era: 'classical', prereq: ['music', 'alphabet', 'painting'], items: { cloth: 4 }, difficulty: 0.9, skill: 'social', minSkill: 0.65, minPop: 15, buildings: ['theatre'], fx: { happiness: 0.2 }, wow: 'Az első színdarab', desc: 'Mások élete a színpadon: nevetnek és sírnak rajta.' });
  T('literature', { name: 'Irodalom', era: 'classical', prereq: ['alphabet', 'theatre'], items: { clay: 4 }, nearby: 'archive', difficulty: 0.91, skill: 'social', minSkill: 0.65, minPop: 15, fx: { teach: 0.15, happiness: 0.1 }, desc: 'Történetek, amelyek túlélik a mesélőt.' });
  T('stadium', { name: 'Stadion', era: 'classical', prereq: ['sports', 'architecture'], items: { stone: 30 }, difficulty: 0.91, skill: 'building', minSkill: 0.7, minPop: 20, buildings: ['stadium'], fx: { happiness: 0.15 }, desc: 'Kőlépcsők a versenypálya körül: a város együtt kiált.' });
  T('fashion', { name: 'Divat', era: 'renaissance', prereq: ['tailoring', 'dyeing', 'trade'], items: { cloth: 6 }, nearby: 'workshop', difficulty: 0.93, skill: 'crafting', minSkill: 0.7, minPop: 20, recipes: ['fine_clothes'], fx: { happiness: 0.1, trade: 0.1 }, desc: 'A ruha nemcsak melegít: beszél.' });
  T('museums', { name: 'Múzeum', era: 'renaissance', prereq: ['printing', 'sculpture'], items: { paper: 4, stone: 10 }, difficulty: 0.94, skill: 'social', minSkill: 0.75, minPop: 26, buildings: ['museum'], fx: { teach: 0.1, happiness: 0.1 }, desc: 'A múlt tárgyai egy házban, mindenkinek.' });
  T('recorded_music', { name: 'Hangfelvétel', era: 'modern', prereq: ['electricity', 'music'], items: { electric_part: 2 }, nearby: 'workshop', difficulty: 0.955, skill: 'crafting', minSkill: 0.8, minPop: 35, fx: { happiness: 0.1 }, desc: 'A dal megmarad, ha az énekes elhallgat.' });
  T('tourism', { name: 'Turizmus', era: 'modern', prereq: ['rail_network', 'photography'], items: { coin: 6 }, difficulty: 0.96, skill: 'social', minSkill: 0.82, minPop: 45, fx: { trade: 0.15, happiness: 0.1, diplomacy: 0.1 }, desc: 'Utazni azért, hogy lássanak.' });
  T('olympics', { name: 'Nagy játékok', era: 'modern', prereq: ['stadium', 'diplomacy', 'rail_network'], items: {}, nearby: 'stadium', difficulty: 0.96, skill: 'social', minSkill: 0.82, minPop: 50, fx: { diplomacy: 0.2, happiness: 0.15 }, wow: 'Az első nagy játékok', desc: 'A városok versenyeznek, nem harcolnak.' });
  T('video_games', { name: 'Videojátékok', era: 'digital', prereq: ['software', 'television'], items: { chip: 4 }, nearby: 'computer_center', difficulty: 0.975, skill: 'crafting', minSkill: 0.85, minPop: 60, fx: { happiness: 0.15, teach: 0.05 }, desc: 'Világok a képernyőn, amelyekben ők a teremtők.' });
  // — hadviselés
  T('cavalry', { name: 'Lovasság', era: 'classical', prereq: ['horse_riding', 'iron_working'], items: { iron: 4, hide: 4 }, difficulty: 0.9, skill: 'hunting', minSkill: 0.65, minPop: 15, fx: { war: 0.3, speed: 0.05 }, desc: 'A ló és a vas együtt: a csata gyorsabb lett.' });
  T('siege_engines', { name: 'Ostromgépek', era: 'classical', prereq: ['mechanics', 'fortification'], items: { wood: 12, iron: 4 }, nearby: 'workshop', difficulty: 0.91, skill: 'crafting', minSkill: 0.7, minPop: 18, fx: { war: 0.3 }, desc: 'A fal nem véd örökké.' });
  T('standing_army', { name: 'Állandó hadsereg', era: 'classical', prereq: ['taxation', 'law_code'], items: { coin: 6 }, difficulty: 0.91, skill: 'social', minSkill: 0.7, minPop: 20, buildings: ['barracks'], fx: { war: 0.3, safety: 0.2 }, desc: 'Katonák, akik békében is katonák.' });
  T('artillery', { name: 'Tüzérség', era: 'renaissance', prereq: ['gunpowder', 'firearms', 'mechanics'], items: { steel: 4, coal: 2 }, nearby: 'forge', difficulty: 0.95, skill: 'crafting', minSkill: 0.82, minPop: 28, fx: { war: 0.4 }, desc: 'Az ágyú előtt a vár is csak kő.' });
  T('conscription', { name: 'Sorozás', era: 'industrial', prereq: ['standing_army', 'bureaucracy'], items: {}, nearby: 'barracks', difficulty: 0.95, skill: 'social', minSkill: 0.8, minPop: 32, fx: { war: 0.3, happiness: -0.05 }, desc: 'Minden fiú katona, ha az állam hívja.' });
  T('armored_vehicles', { name: 'Páncélosok', era: 'modern', prereq: ['automobile', 'artillery', 'steel_making'], items: { steel: 12, machine_part: 6 }, nearby: 'factory', difficulty: 0.965, skill: 'crafting', minSkill: 0.88, minPop: 50, fx: { war: 0.5 }, desc: 'Acélba zárt tűz, lánctalpon.' });
  T('military_aviation', { name: 'Harci repülés', era: 'modern', prereq: ['aviation', 'artillery'], items: { steel: 8, fuel: 4 }, nearby: 'factory', difficulty: 0.965, skill: 'crafting', minSkill: 0.88, minPop: 50, fx: { war: 0.5 }, desc: 'A háború fölülről jön.' });
  T('jet_engine', { name: 'Sugárhajtómű', era: 'modern', prereq: ['aviation', 'metallurgy'], items: { steel: 10, machine_part: 6, fuel: 4 }, nearby: 'factory', difficulty: 0.97, skill: 'crafting', minSkill: 0.88, minPop: 55, fx: { speed: 0.2, war: 0.2 }, desc: 'Gyorsabb a hangnál.' });
  T('nuclear_weapons', { name: 'Atomfegyver', era: 'modern', prereq: ['nuclear_fission', 'rocketry'], items: { steel: 10, electric_part: 10 }, nearby: 'lab', difficulty: 0.978, skill: 'crafting', minSkill: 0.92, minPop: 70, fx: { war: 1.5, diplomacy: 0.3 }, wow: 'A bomba', desc: 'Egyetlen fegyver, amely egy várost töröl el — és éppen ezért senki sem meri használni. Majdnem.' });
  T('cyberwarfare', { name: 'Kiberhadviselés', era: 'ai', prereq: ['internet', 'cryptography'], items: { chip: 8 }, nearby: 'data_center', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 80, fx: { war: 0.3, safety: -0.05 }, desc: 'A háború a vezetékekben folyik.' });
  T('drones', { name: 'Drónok', era: 'ai', prereq: ['robotics', 'military_aviation', 'machine_learning'], items: { chip: 10, machine_part: 4 }, nearby: 'robot_factory', difficulty: 0.982, skill: 'crafting', minSkill: 0.92, minPop: 90, fx: { war: 0.4, hunt: 0.2 }, desc: 'Szárnyak pilóta nélkül.' });
  // — űr
  T('observatory', { name: 'Csillagvizsgáló', era: 'renaissance', prereq: ['optics', 'astronomy'], items: { glass: 6, brick: 10 }, difficulty: 0.94, skill: 'building', minSkill: 0.75, minPop: 22, buildings: ['observatory'], fx: { discovery: 0.15 }, wow: 'Az első csillagvizsgáló', desc: 'Egy ház, amely csak az eget nézi.' });
  T('space_station', { name: 'Űrállomás', era: 'digital', prereq: ['spaceflight', 'satellites'], items: { steel: 30, chip: 20, electric_part: 20 }, nearby: 'computer_center', difficulty: 0.983, skill: 'crafting', minSkill: 0.93, minPop: 100, buildings: ['spaceport'], fx: { discovery: 0.2 }, wow: 'Az első űrállomás', desc: 'Emberek laknak az ég fölött.' });
  T('moon_landing', { name: 'Holdra szállás', era: 'digital', prereq: ['spaceflight', 'computer', 'rocketry'], items: { fuel: 20, steel: 20, chip: 10 }, nearby: 'spaceport', difficulty: 0.984, skill: 'crafting', minSkill: 0.94, minPop: 100, fx: { discovery: 0.2, happiness: 0.2 }, wow: 'Az első lábnyom a Holdon', desc: 'Az égi fény, amelyre eddig csak imádkoztak, most föld a talpuk alatt.' });
  T('space_telescope', { name: 'Űrtávcső', era: 'digital', prereq: ['satellites', 'optics'], items: { chip: 12, glass: 10 }, nearby: 'spaceport', difficulty: 0.982, skill: 'crafting', minSkill: 0.92, minPop: 95, fx: { discovery: 0.3 }, desc: 'A világegyetem széléig lát.' });
  T('mars_landing', { name: 'Marsra szállás', era: 'ai', prereq: ['moon_landing', 'robotics'], items: { fuel: 40, steel: 40, chip: 30 }, nearby: 'spaceport', difficulty: 0.987, skill: 'crafting', minSkill: 0.95, minPop: 105, fx: { discovery: 0.2, happiness: 0.15 }, wow: 'Az első lábnyom a Marson', desc: 'Egy másik világ pora.' });
  T('asteroid_mining', { name: 'Aszteroidabányászat', era: 'ai', prereq: ['mars_landing', 'robotics'], items: { chip: 30, steel: 30 }, nearby: 'spaceport', difficulty: 0.988, skill: 'crafting', minSkill: 0.95, minPop: 105, fx: { mine: 1, craft: 0.3 }, wow: 'Érc az égből', desc: 'A hegyek elfogynak; az ég nem.' });
  T('space_colony', { name: 'Űrkolónia', era: 'ai', prereq: ['mars_landing', 'vertical_farming', 'fusion'], items: { chip: 60, concrete: 40, steel: 40 }, nearby: 'spaceport', difficulty: 0.99, skill: 'building', minSkill: 0.96, minPop: 110, fx: { discovery: 0.2 }, wow: 'Az első telepesek az égben', desc: 'Néhányan elmennek, és nem jönnek vissza: új világot kezdenek a világon kívül.' });
  // — gépi elme
  T('agi', { name: 'Általános mesterséges intelligencia', era: 'ai', prereq: ['artificial_intelligence', 'quantum_computing', 'neuroscience'], items: { chip: 80 }, nearby: 'data_center', difficulty: 0.989, skill: 'crafting', minSkill: 0.96, minPop: 110, buildings: ['ai_core'], fx: { discovery: 0.6, teach: 0.5, craft: 0.3 }, wow: 'Egy elme, amely nem született', desc: 'Gondolkodik, tanul, tanít — és ők nem tudják, mit gondol róluk.' });
  T('brain_computer_interface', { name: 'Agy–gép kapcsolat', era: 'ai', prereq: ['neuroscience', 'integrated_circuit'], items: { chip: 20, medicine: 6 }, nearby: 'hospital', difficulty: 0.987, skill: 'medicine', minSkill: 0.95, minPop: 105, fx: { teach: 0.6, discovery: 0.2 }, wow: 'A gondolat, amely kilép a fejből', desc: 'Az elme közvetlenül beszél a géppel.' });
  T('mind_uploading', { name: 'Elmefeltöltés', era: 'ai', prereq: ['brain_computer_interface', 'world_simulation'], items: { chip: 100, medicine: 10 }, nearby: 'simulation_core', difficulty: 0.992, skill: 'medicine', minSkill: 0.97, minPop: 115, fx: { longevity: 30, discovery: 0.3 }, wow: 'Az első átköltözött elme', desc: 'Aki nem akar meghalni, átköltözik a világba, amelyet ők teremtettek.' });

  // ---------------------------------------------------------------- hatások az épületekből: erőmű, állomás, adótorony, színház, őrség, bank
  const fx0 = Tree.fx; const TPD = LW.TIME.TICKS_PER_DAY;
  Tree.fx = function (world, a) {
    const base = fx0.call(this, world, a); const day = world.tick / TPD | 0;
    if (a._fxb && a._fxbDay === day && a._fxbN === a.knowledge.techs.size && a._fxbX === (a.x | 0) >> 3 && a._fxbY === (a.y | 0) >> 3) return a._fxb;
    const g = { ...base }; let power = 0, transport = 0, media = 0, joy = 0, guard = 0, bank = 0;
    for (const b of world.buildingsNear(a.x | 0, a.y | 0, 10)) { if (b.progress < 1) continue; const d = B[b.kind]; if (!d) continue; if (d.power > power) power = d.power; if (d.transport > transport) transport = d.transport; if (d.media > media) media = d.media; if (d.joy > joy) joy = d.joy; if ((d.police || d.court || d.barracks) && 1 > guard) guard = 1; if (d.bank > bank) bank = d.bank; }
    g.craft += power * 0.1; g.warmth += power * 1.5; g.speed += transport * 0.2; g.trade += transport * 0.2 + bank * 0.2; g.teach += media * 0.2; g.happiness += joy * 0.08; g.safety += guard * 0.2;
    g.speed -= this.bestTool(a, 'vehicle') * 0.25; // szekér/kerékpár/gépkocsi: 0.25 fokonként (az alap 0.5/fok helyett)
    g.craft += this.bestTool(a, 'robot') * 0.3; g.build += this.bestTool(a, 'robot') * 0.3; g.farm += this.bestTool(a, 'robot') * 0.2;
    a._fxb = g; a._fxbDay = day; a._fxbN = a.knowledge.techs.size; a._fxbX = (a.x | 0) >> 3; a._fxbY = (a.y | 0) >> 3; return g;
  };
  Tree.DOMAINS = [['Átkelők, infrastruktúra', ['bridge_building', 'stone_bridges', 'suspension_bridges', 'tunneling', 'aqueducts', 'paved_roads', 'canals', 'sewers', 'dam_building', 'water_supply', 'urban_planning', 'skyscrapers']], ['Közlekedés', ['wheel', 'horse_riding', 'shipbuilding', 'compass', 'steamship', 'rail_network', 'bicycle', 'civil_aviation', 'container_shipping', 'electric_vehicles', 'autonomous_vehicles']], ['Energia', ['watermill', 'windmill', 'coal_power', 'battery', 'power_grid', 'hydropower', 'wind_power', 'solar_power', 'nuclear_power', 'fusion_power']], ['Anyagok, ipar', ['porcelain', 'metallurgy', 'canning', 'aluminium', 'synthetic_fibers', 'assembly_line', 'recycling', 'additive_manufacturing', 'robotics', 'automation', 'nanotech']], ['Mezőgazdaság', ['beekeeping', 'salting', 'viticulture', 'terrace_farming', 'aquaculture', 'selective_breeding', 'greenhouses', 'fertilizers', 'mechanized_farming', 'refrigeration', 'gmo', 'vertical_farming']], ['Orvoslás', ['surgery', 'quarantine', 'germ_theory', 'anesthesia', 'antibiotics', 'psychology', 'public_health', 'family_planning', 'medical_imaging', 'organ_transplant', 'neuroscience', 'gene_therapy', 'life_extension']], ['Kommunikáció', ['postal_service', 'newspaper', 'photography', 'telephone', 'cinema', 'television', 'cryptography', 'mobile_phone', 'satellites', 'social_networks', 'quantum_computing']], ['Tudományok', ['geometry', 'philosophy', 'theology', 'physics', 'biology', 'geology', 'economics', 'statistics', 'evolution', 'relativity', 'quantum_mechanics', 'climate_science', 'unified_theory']], ['Társadalom, gazdaság', ['bureaucracy', 'taxation', 'courts', 'diplomacy', 'democracy', 'guilds', 'constitution', 'insurance', 'police', 'stock_market', 'universal_education', 'labor_unions', 'welfare_state', 'international_law']], ['Kultúra', ['music', 'painting', 'sports', 'sculpture', 'theatre', 'literature', 'stadium', 'fashion', 'museums', 'recorded_music', 'tourism', 'olympics', 'video_games']], ['Hadviselés', ['cavalry', 'siege_engines', 'standing_army', 'artillery', 'conscription', 'armored_vehicles', 'military_aviation', 'jet_engine', 'nuclear_weapons', 'cyberwarfare', 'drones']], ['Űr', ['observatory', 'space_station', 'moon_landing', 'space_telescope', 'mars_landing', 'asteroid_mining', 'space_colony']], ['Gépi elme', ['agi', 'brain_computer_interface', 'mind_uploading']]];

  // ---------------------------------------------------------------- az ismeretlen jövő: gazdagabb, területenként, valódi hatással
  const FUTURE = {
    domains: [['anyag', ['Kvantum', 'Nano', 'Meta', 'Plazma', 'Foton'], ['kohó', 'szövet', 'burok', 'rács', 'ötvözet'], ['craft', 'build', 'mine']], ['élet', ['Bio', 'Neuro', 'Ön', 'Szimbi', 'Gén'], ['sejt', 'kert', 'mag', 'lánc', 'szív'], ['health', 'longevity', 'farm', 'fertility']], ['elme', ['Neuro', 'Meta', 'Szinguláris', 'Kripto', 'Holo'], ['elme', 'nyelv', 'tükör', 'kapu', 'háló'], ['discovery', 'teach', 'happiness']], ['tér', ['Gravi', 'Tér', 'Idő', 'Hiper', 'Exo'], ['híd', 'motor', 'vető', 'térkép', 'kút'], ['speed', 'trade', 'discovery', 'safety']], ['társadalom', ['Pán', 'Kollektív', 'Nyílt', 'Tiszta', 'Örök'], ['tanács', 'szerződés', 'kör', 'ének', 'béke'], ['diplomacy', 'happiness', 'safety', 'trade']]],
    flavors: ['Az anyag új rendje.', 'A gondolat új alakja.', 'Az idő másképp folyik körülötte.', 'A világ széle közelebb jött.', 'Senki nem tudja, mire jó — még.', 'A Teremtő sem érti, de ők igen.', 'Ami eddig lehetetlen volt, most csak drága.', 'Egy kérdés, amelyre a válasz újabb kérdés.'],
  };
  Tree.futureStep = function (world) {
    const known = LW.Tech.worldKnowledge(world); if (!known.has('world_simulation')) return;
    world.futureTechs = world.futureTechs || []; const last = world.futureTechs[world.futureTechs.length - 1];
    if (last && !known.has(last.id)) return; // előbb az utolsó ismeretlent kell megtalálni
    if (last && world.tick - last.born < LW.TIME.TICKS_PER_YEAR * 2) return;
    const rng = world.rng; const n = world.futureTechs.length + 1; const [dom, pre, root, keys] = rng.pick(FUTURE.domains);
    const name = `${rng.pick(pre)}${rng.pick(root)}`; const fx = {}; for (const k of rng.shuffle(keys.slice()).slice(0, rng.int(1, 2))) fx[k] = k === 'longevity' ? rng.int(3, 12) : Math.round(rng.range(0.15, 0.5) * 100) / 100;
    const own = world.language.place().toLowerCase(); const nearby = rng.pick(['data_center', 'lab', 'simulation_core', 'ai_core', 'spaceport']);
    const t = { id: `future_${n}`, name, era: 'beyond', domain: dom, prereq: [last ? last.id : 'world_simulation'], items: { chip: rng.int(10, 60), electric_part: rng.int(4, 20) }, nearby: B[nearby] ? nearby : 'data_center', difficulty: 0.985 + rng.f() * 0.012, skill: rng.pick(['crafting', 'medicine', 'building', 'social']), minSkill: 0.9, minPop: 105 + n * 15, fx, wow: `Ismeretlen: ${name}`, desc: `Amit még senki nem látott (${dom}). Ők úgy hívják: „${own}”. ${rng.pick(FUTURE.flavors)}`, born: world.tick };
    world.futureTechs.push(t); this.registerFuture([t]);
    world.events.emit('FutureTech', { tick: world.tick, name, id: t.id, domain: dom });
  };
})(globalThis.LW || (globalThis.LW = {}));
