/* LEVENTE — THE CREATOR · tech/tree.js — a világ „természettörvényei”: minden, ami felfedezhető
 * Nem történelem, hanem lehetőségtér: mi miből lesz, mihez kell tűz, kemence, műhely, írás, sok ember.
 * Az emberek maguk találják meg (kísérlet, véletlen, tanítás, olvasás) — vagy soha. (TECHNOLOGY_MODEL.md)
 */
(function (LW) {
  'use strict';
  const D = LW.Tech.D, R = LW.Tech.RECIPES, S = LW.Tech.SOURCE, I = LW.ITEMS, B = LW.Buildings.DEFS; const TPD = LW.TIME.TICKS_PER_DAY;

  // ---------------------------------------------------------------- korszakok
  const ERAS = [['primitive', 'Kezdetleges'], ['neolithic', 'Újkőkor'], ['copper', 'Rézkor'], ['bronze', 'Bronzkor'], ['iron', 'Vaskor'], ['classical', 'Ókor'], ['medieval', 'Középkor'], ['renaissance', 'Reneszánsz'], ['industrial', 'Ipari kor'], ['modern', 'Modern kor'], ['digital', 'Digitális kor'], ['ai', 'MI-kor'], ['beyond', 'Ismeretlen jövő']];
  const ERA_INDEX = {}; ERAS.forEach(([k], i) => { ERA_INDEX[k] = i; });

  // ---------------------------------------------------------------- tárgyak
  Object.assign(I, {
    charcoal: { weight: 0.8, label: 'Faszén' }, copper: { weight: 1.5, label: 'Réz' }, tin: { weight: 1.5, label: 'Ón' }, bronze: { weight: 1.5, label: 'Bronz' }, iron: { weight: 2, label: 'Vas' }, steel: { weight: 2, label: 'Acél' },
    cloth: { weight: 0.4, label: 'Vászon' }, brick: { weight: 1.5, label: 'Tégla' }, paper: { weight: 0.2, label: 'Papír' }, glass: { weight: 0.8, label: 'Üveg' }, coin: { weight: 0.05, label: 'Érme' }, book: { weight: 0.5, label: 'Könyv' },
    flour: { food: 0.35, spoilDays: 120, weight: 0.5, label: 'Liszt' }, bread: { food: 0.65, spoilDays: 12, weight: 0.5, label: 'Kenyér' }, beer: { food: 0.2, water: 0.3, spoilDays: 40, weight: 0.8, label: 'Sör' }, cheese: { food: 0.5, spoilDays: 60, weight: 0.5, label: 'Sajt' }, fruit: { food: 0.35, water: 0.1, spoilDays: 8, weight: 0.5, label: 'Gyümölcs' }, milk: { food: 0.25, water: 0.4, spoilDays: 2, weight: 0.8, label: 'Tej' },
    oil: { weight: 1.5, label: 'Fekete olaj' }, fuel: { weight: 1, label: 'Üzemanyag' }, plastic: { weight: 0.5, label: 'Műanyag' }, concrete: { weight: 2, label: 'Beton' }, machine_part: { weight: 2, label: 'Gépalkatrész' }, electric_part: { weight: 1, label: 'Elektromos alkatrész' }, chip: { weight: 0.1, label: 'Csip' }, medicine: { weight: 0.2, label: 'Orvosság' }, wool: { weight: 0.4, label: 'Gyapjú' },
    copper_axe: { weight: 1.5, label: 'Rézbalta', tool: true, slot: 'axe', tier: 1 }, bronze_axe: { weight: 1.5, label: 'Bronzbalta', tool: true, slot: 'axe', tier: 2 }, iron_axe: { weight: 1.8, label: 'Vasbalta', tool: true, slot: 'axe', tier: 3 }, steel_axe: { weight: 1.8, label: 'Acélbalta', tool: true, slot: 'axe', tier: 4 }, chainsaw: { weight: 3, label: 'Láncfűrész', tool: true, slot: 'axe', tier: 6 },
    bow: { weight: 1, label: 'Íj', tool: true, slot: 'hunt', tier: 2 }, bronze_spear: { weight: 1.3, label: 'Bronzlándzsa', tool: true, slot: 'hunt', tier: 2 }, iron_spear: { weight: 1.4, label: 'Vaslándzsa', tool: true, slot: 'hunt', tier: 3 }, rifle: { weight: 3, label: 'Puska', tool: true, slot: 'hunt', tier: 5 },
    wooden_plow: { weight: 3, label: 'Faeke', tool: true, slot: 'plow', tier: 1 }, bronze_plow: { weight: 3, label: 'Bronzeke', tool: true, slot: 'plow', tier: 2 }, iron_plow: { weight: 3.5, label: 'Vaseke', tool: true, slot: 'plow', tier: 3 }, tractor: { weight: 10, label: 'Traktor', tool: true, slot: 'plow', tier: 6 },
    pickaxe: { weight: 2, label: 'Csákány', tool: true, slot: 'mine', tier: 2 }, iron_pickaxe: { weight: 2.2, label: 'Vascsákány', tool: true, slot: 'mine', tier: 3 }, drill: { weight: 4, label: 'Fúrógép', tool: true, slot: 'mine', tier: 5 },
    wool_clothes: { weight: 1, label: 'Gyapjúruha', tool: true, warmth: 11, slot: 'clothes', tier: 2 }, boat: { weight: 0, label: 'Csónak', tool: true, slot: 'boat', tier: 1 }, car: { weight: 0, label: 'Gépkocsi', tool: true, slot: 'vehicle', tier: 1 }, coat: { weight: 1.2, label: 'Kabát', tool: true, warmth: 14, slot: 'clothes', tier: 3 },
  });
  I.clothes.slot = 'clothes'; I.clothes.tier = 1; I.handaxe.slot = 'axe'; I.handaxe.tier = 0.5; I.spear.slot = 'hunt'; I.spear.tier = 1;
  LW.DEPOSIT_ITEM[10] = 'oil';
  Object.assign(S, { coal: 'deposit:coal', ore_copper: 'deposit:copper', ore_tin: 'deposit:tin', ore_iron: 'deposit:iron', gold_nugget: 'deposit:gold', gems: 'deposit:gems', salt: 'deposit:salt', oil: 'deposit:oil', grain: 'store', fruit: 'store', milk: 'store', wool: 'store' });

  // ---------------------------------------------------------------- receptek (miből mi lesz, hol)
  Object.assign(R, {
    charcoal: { out: { charcoal: 2 }, inp: { wood: 4 }, ticks: 24, tech: 'charcoal_making', nearby: 'fire', skill: 'crafting', tag: 'craft:charcoal' },
    copper: { out: { copper: 1 }, inp: { ore_copper: 2, charcoal: 1 }, ticks: 30, tech: 'copper_smelting', nearby: 'furnace', skill: 'crafting', tag: 'craft:smelt' },
    tin: { out: { tin: 1 }, inp: { ore_tin: 2, charcoal: 1 }, ticks: 30, tech: 'bronze_alloy', nearby: 'furnace', skill: 'crafting', tag: 'craft:smelt' },
    bronze: { out: { bronze: 2 }, inp: { copper: 2, tin: 1 }, ticks: 30, tech: 'bronze_alloy', nearby: 'furnace', skill: 'crafting', tag: 'craft:smelt' },
    iron: { out: { iron: 1 }, inp: { ore_iron: 2, charcoal: 2 }, ticks: 40, tech: 'iron_smelting', nearby: 'furnace', skill: 'crafting', tag: 'craft:smelt' },
    steel: { out: { steel: 1 }, inp: { iron: 2, coal: 1 }, ticks: 40, tech: 'steel_making', nearby: 'forge', skill: 'crafting', tag: 'craft:smelt' },
    cloth: { out: { cloth: 1 }, inpAny: [{ fiber: 6 }, { wool: 3 }], ticks: 30, tech: 'weaving', skill: 'crafting', tag: 'craft:weave' },
    wool_clothes: { out: { wool_clothes: 1 }, inp: { cloth: 2 }, ticks: 24, tech: 'weaving', skill: 'crafting', tag: 'craft:clothes' },
    coat: { out: { coat: 1 }, inp: { cloth: 2, hide: 1 }, ticks: 30, tech: 'tailoring', nearby: 'workshop', skill: 'crafting', tag: 'craft:clothes' },
    brick: { out: { brick: 2 }, inp: { clay: 4 }, ticks: 20, tech: 'brick_making', nearby: 'kiln', skill: 'crafting', tag: 'craft:brick' },
    paper: { out: { paper: 2 }, inp: { fiber: 4, wood: 2 }, ticks: 30, tech: 'paper_making', nearby: 'workshop', skill: 'crafting', tag: 'craft:paper' },
    glass: { out: { glass: 1 }, inp: { stone: 3, charcoal: 1 }, ticks: 30, tech: 'glassmaking', nearby: 'furnace', skill: 'crafting', tag: 'craft:glass' },
    coin: { out: { coin: 6 }, inpAny: [{ gold_nugget: 1 }, { copper: 2 }], ticks: 20, tech: 'coinage', nearby: 'workshop', skill: 'crafting', tag: 'craft:coin' },
    book: { out: { book: 1 }, inp: { paper: 4 }, ticks: 40, tech: 'printing', nearby: 'workshop', skill: 'crafting', tag: 'craft:book' },
    flour: { out: { flour: 2 }, inp: { grain: 3 }, ticks: 12, tech: 'milling', nearby: 'mill', skill: 'crafting', tag: 'craft:flour' },
    bread: { out: { bread: 2 }, inp: { flour: 1 }, ticks: 10, tech: 'baking', nearby: 'fire', skill: 'crafting', tag: 'craft:bread' },
    beer: { out: { beer: 2 }, inp: { grain: 3 }, ticks: 30, tech: 'brewing', skill: 'crafting', tag: 'craft:beer' },
    cheese: { out: { cheese: 1 }, inp: { milk: 2, salt: 1 }, ticks: 30, tech: 'dairy', skill: 'crafting', tag: 'craft:cheese' },
    copper_axe: { out: { copper_axe: 1 }, inp: { copper: 2, wood: 1 }, ticks: 20, tech: 'copper_tools', nearby: 'furnace', skill: 'crafting', tag: 'craft:tool' },
    bronze_axe: { out: { bronze_axe: 1 }, inp: { bronze: 2, wood: 1 }, ticks: 20, tech: 'bronze_tools', nearby: 'furnace', skill: 'crafting', tag: 'craft:tool' },
    bronze_spear: { out: { bronze_spear: 1 }, inp: { bronze: 1, wood: 1, fiber: 1 }, ticks: 16, tech: 'bronze_tools', nearby: 'furnace', skill: 'crafting', tag: 'craft:tool' },
    bow: { out: { bow: 1 }, inp: { wood: 2, fiber: 3 }, ticks: 24, tech: 'archery', skill: 'crafting', tag: 'craft:tool' },
    pickaxe: { out: { pickaxe: 1 }, inp: { bronze: 2, wood: 1 }, ticks: 20, tech: 'mining', nearby: 'furnace', skill: 'crafting', tag: 'craft:tool' },
    iron_axe: { out: { iron_axe: 1 }, inp: { iron: 2, wood: 1 }, ticks: 24, tech: 'iron_working', nearby: 'forge', skill: 'crafting', tag: 'craft:tool' },
    iron_spear: { out: { iron_spear: 1 }, inp: { iron: 1, wood: 1 }, ticks: 20, tech: 'iron_working', nearby: 'forge', skill: 'crafting', tag: 'craft:tool' },
    iron_pickaxe: { out: { iron_pickaxe: 1 }, inp: { iron: 2, wood: 1 }, ticks: 24, tech: 'iron_working', nearby: 'forge', skill: 'crafting', tag: 'craft:tool' },
    steel_axe: { out: { steel_axe: 1 }, inp: { steel: 2, wood: 1 }, ticks: 24, tech: 'steel_making', nearby: 'forge', skill: 'crafting', tag: 'craft:tool' },
    wooden_plow: { out: { wooden_plow: 1 }, inp: { wood: 5 }, ticks: 30, tech: 'plowing', skill: 'crafting', tag: 'craft:tool' },
    bronze_plow: { out: { bronze_plow: 1 }, inp: { bronze: 2, wood: 3 }, ticks: 30, tech: 'bronze_tools', nearby: 'furnace', skill: 'crafting', tag: 'craft:tool' },
    iron_plow: { out: { iron_plow: 1 }, inp: { iron: 2, wood: 3 }, ticks: 30, tech: 'iron_working', nearby: 'forge', skill: 'crafting', tag: 'craft:tool' },
    machine_part: { out: { machine_part: 2 }, inp: { iron: 2, wood: 1 }, ticks: 40, tech: 'mechanics', nearby: 'workshop', skill: 'crafting', tag: 'craft:machine' },
    electric_part: { out: { electric_part: 2 }, inp: { copper: 2, iron: 1 }, ticks: 40, tech: 'electricity', nearby: 'workshop', skill: 'crafting', tag: 'craft:machine' },
    concrete: { out: { concrete: 3 }, inp: { stone: 4, clay: 2 }, ticks: 24, tech: 'concrete', nearby: 'kiln', skill: 'building', tag: 'craft:concrete' },
    fuel: { out: { fuel: 2 }, inp: { oil: 2 }, ticks: 30, tech: 'oil_refining', nearby: 'factory', skill: 'crafting', tag: 'craft:refine' },
    plastic: { out: { plastic: 2 }, inp: { oil: 2 }, ticks: 30, tech: 'plastics', nearby: 'factory', skill: 'crafting', tag: 'craft:refine' },
    medicine: { out: { medicine: 2 }, inp: { fiber: 2, berries: 2, glass: 1 }, ticks: 40, tech: 'pharmacology', nearby: 'lab', skill: 'medicine', tag: 'craft:medicine' },
    chip: { out: { chip: 4 }, inp: { glass: 1, copper: 1, electric_part: 1 }, ticks: 60, tech: 'integrated_circuit', nearby: 'lab', skill: 'crafting', tag: 'craft:chip' },
    rifle: { out: { rifle: 1 }, inp: { steel: 2, wood: 1, machine_part: 1 }, ticks: 40, tech: 'firearms', nearby: 'workshop', skill: 'crafting', tag: 'craft:tool' },
    drill: { out: { drill: 1 }, inp: { steel: 2, machine_part: 2 }, ticks: 40, tech: 'machine_tools', nearby: 'factory', skill: 'crafting', tag: 'craft:tool' },
    chainsaw: { out: { chainsaw: 1 }, inp: { steel: 2, machine_part: 2, fuel: 1 }, ticks: 40, tech: 'internal_combustion', nearby: 'factory', skill: 'crafting', tag: 'craft:tool' },
    tractor: { out: { tractor: 1 }, inp: { steel: 6, machine_part: 6, fuel: 2 }, ticks: 120, tech: 'internal_combustion', nearby: 'factory', skill: 'crafting', tag: 'craft:tool' },
    boat: { out: { boat: 1 }, inp: { wood: 8, fiber: 4 }, ticks: 80, tech: 'boatbuilding', skill: 'building', tag: 'craft:boat' },
    car: { out: { car: 1 }, inp: { steel: 6, machine_part: 4, fuel: 2 }, ticks: 120, tech: 'automobile', nearby: 'factory', skill: 'crafting', tag: 'craft:tool' },
  });

  // ---------------------------------------------------------------- épületek
  const pub = (o) => Object.assign({ public: true }, o);
  Object.assign(B, {
    granary: pub({ label: 'Magtár', cost: { wood: 12, clay: 6, stone: 4 }, ticks: 220, storage: 200, preserve: 0.85, tech: 'granary_building', lifeDays: 4000, want: 'food', minPop: 3 }),
    well: pub({ label: 'Kút', cost: { stone: 12, wood: 4 }, ticks: 160, water: true, tech: 'well_digging', lifeDays: 12000, want: 'water', minPop: 2 }),
    orchard: { label: 'Gyümölcsös', cost: { wood: 4 }, ticks: 120, farm: true, cropItem: 'fruit', cropDays: 200, yieldBase: 40, perennial: true, tech: 'horticulture', lifeDays: 6000, size: [2, 2] },
    pasture: { label: 'Karám', cost: { wood: 10, fiber: 4 }, ticks: 160, pasture: true, tech: 'animal_husbandry', lifeDays: 3000, size: [2, 2] },
    kiln: pub({ label: 'Égetőkemence', cost: { clay: 10, stone: 8 }, ticks: 160, furnace: 1, kiln: true, tech: 'kiln_building', lifeDays: 3000, light: 0.3, minPop: 2 }),
    furnace: pub({ label: 'Olvasztókemence', cost: { stone: 16, clay: 10, wood: 6 }, ticks: 260, furnace: 2, storage: 60, tech: 'copper_smelting', lifeDays: 4000, light: 0.4, minPop: 3 }),
    workshop: pub({ label: 'Műhely', cost: { wood: 18, stone: 6, fiber: 4 }, ticks: 240, workshop: 1, craft: 0.3, storage: 80, tech: 'carpentry', lifeDays: 4000, minPop: 3 }),
    forge: pub({ label: 'Kovácsműhely', cost: { stone: 20, wood: 14, iron: 4 }, ticks: 360, furnace: 3, forge: true, workshop: 1, craft: 0.4, storage: 80, tech: 'iron_working', lifeDays: 6000, light: 0.5, minPop: 5 }),
    shrine: pub({ label: 'Szentély', cost: { stone: 10, wood: 6 }, ticks: 200, shrine: 1, tech: 'ritual', lifeDays: 12000, light: 0.2, want: 'belief', minPop: 3 }),
    temple: pub({ label: 'Templom', cost: { stone: 40, brick: 10, wood: 12 }, ticks: 900, shrine: 2, tech: 'organized_religion', lifeDays: 30000, light: 0.5, want: 'belief', minPop: 12, size: [2, 2] }),
    archive: pub({ label: 'Levéltár', cost: { clay: 12, wood: 10, stone: 6 }, ticks: 300, records: 1, tech: 'writing', lifeDays: 12000, minPop: 5, want: 'knowledge' }),
    library: pub({ label: 'Könyvtár', cost: { stone: 24, wood: 16, paper: 6 }, ticks: 600, records: 2, teach: 0.3, tech: 'paper_making', lifeDays: 20000, minPop: 12, want: 'knowledge', size: [2, 1] }),
    school: pub({ label: 'Iskola', cost: { wood: 20, stone: 10, brick: 6 }, ticks: 500, school: 1, teach: 0.4, tech: 'schooling', lifeDays: 12000, minPop: 10, want: 'knowledge' }),
    university: pub({ label: 'Egyetem', cost: { stone: 40, brick: 30, glass: 6, paper: 10 }, ticks: 1400, school: 2, records: 2, discovery: 0.35, teach: 0.5, tech: 'universities', lifeDays: 40000, minPop: 21, want: 'knowledge', size: [2, 2] }),
    market: pub({ label: 'Piac', cost: { wood: 14, stone: 8, cloth: 4 }, ticks: 300, market: 1, storage: 150, tech: 'trade', lifeDays: 8000, minPop: 8, want: 'food' }),
    mill: pub({ label: 'Malom', cost: { wood: 24, stone: 12 }, ticks: 500, mill: 1, storage: 100, tech: 'milling', lifeDays: 10000, minPop: 8, want: 'food' }),
    irrigation: pub({ label: 'Öntözőcsatorna', cost: { stone: 20, wood: 6 }, ticks: 400, irrigation: 1, tech: 'irrigation', lifeDays: 10000, minPop: 8, want: 'food' }),
    brick_house: { label: 'Téglaház', cost: { brick: 30, wood: 12 }, ticks: 500, insulation: 20, safety: 0.9, sleep: 0.95, capacity: 6, storage: 100, dwelling: true, tier: 4, tech: 'brick_making', lifeDays: 15000, light: 0.7 },
    town_house: { label: 'Városi ház', cost: { brick: 40, wood: 20, glass: 4 }, ticks: 800, insulation: 22, safety: 0.92, sleep: 1, capacity: 8, storage: 160, dwelling: true, tier: 5, tech: 'architecture', lifeDays: 25000, light: 0.8, size: [2, 1] },
    modern_house: { label: 'Modern ház', cost: { concrete: 30, glass: 10, electric_part: 4 }, ticks: 900, insulation: 26, safety: 0.95, sleep: 1, capacity: 6, storage: 200, dwelling: true, tier: 6, tech: 'electrification', lifeDays: 30000, light: 1, size: [2, 1] },
    printing_house: pub({ label: 'Nyomda', cost: { wood: 20, machine_part: 4, paper: 10 }, ticks: 600, records: 3, teach: 0.6, tech: 'printing', lifeDays: 15000, minPop: 15, want: 'knowledge' }),
    lab: pub({ label: 'Laboratórium', cost: { brick: 30, glass: 20, machine_part: 6 }, ticks: 1200, lab: 1, discovery: 0.5, tech: 'scientific_method', lifeDays: 15000, minPop: 18, want: 'knowledge', size: [2, 1] }),
    factory: pub({ label: 'Gyár', cost: { brick: 60, iron: 20, machine_part: 10 }, ticks: 2000, factory: 1, craft: 0.8, storage: 300, tech: 'factory_system', lifeDays: 20000, light: 0.8, minPop: 28, size: [3, 2] }),
    power_plant: pub({ label: 'Erőmű', cost: { brick: 60, steel: 20, machine_part: 20, electric_part: 10 }, ticks: 2400, power: 1, tech: 'electrification', lifeDays: 20000, light: 1.2, minPop: 35, size: [2, 2] }),
    hospital: pub({ label: 'Kórház', cost: { brick: 50, glass: 10, medicine: 10 }, ticks: 1400, hospital: 1, tech: 'modern_medicine', lifeDays: 20000, light: 0.8, minPop: 28, want: 'health', size: [2, 2] }),
    computer_center: pub({ label: 'Számítóközpont', cost: { concrete: 40, electric_part: 30, chip: 20 }, ticks: 2400, computer: 1, discovery: 0.6, records: 4, tech: 'computer', lifeDays: 20000, light: 1, minPop: 42, want: 'knowledge', size: [2, 2] }),
    data_center: pub({ label: 'Adatközpont', cost: { concrete: 60, chip: 80, electric_part: 40 }, ticks: 3000, computer: 2, records: 5, discovery: 0.8, teach: 1, tech: 'internet', lifeDays: 20000, light: 1, minPop: 70, want: 'knowledge', size: [3, 2] }),
    palisade: pub({ label: 'Palánk', cost: { wood: 20, fiber: 4 }, ticks: 300, safety: 0.6, wall: 1, tech: 'fortification', lifeDays: 5000, minPop: 5, want: 'safety' }),
    stone_wall: pub({ label: 'Kőfal', cost: { stone: 40, clay: 8 }, ticks: 700, safety: 0.8, wall: 2, tech: 'stone_walls', lifeDays: 30000, minPop: 10, want: 'safety', size: [2, 1] }),
    castle: pub({ label: 'Vár', cost: { stone: 90, brick: 30, wood: 30, iron: 6 }, ticks: 2600, safety: 0.95, wall: 3, records: 1, storage: 200, tech: 'castles', lifeDays: 60000, light: 0.6, minPop: 20, want: 'safety', size: [3, 3] }),
    harbor: pub({ label: 'Kikötő', cost: { wood: 30, stone: 10, cloth: 4 }, ticks: 600, harbor: 1, storage: 120, tech: 'sailing', lifeDays: 12000, minPop: 8, want: 'food', size: [2, 1] }),
    simulation_core: pub({ label: 'Világmag', cost: { chip: 200, concrete: 80, electric_part: 80 }, ticks: 5000, simulation: 1, tech: 'world_simulation', lifeDays: 1e6, light: 1.5, minPop: 105, want: 'knowledge', size: [3, 3] }),
  });
  B.lean_to.tier = 1; B.hut.tier = 2; B.stone_house.tier = 3;

  // ---------------------------------------------------------------- felfedezések
  const T = (id, o) => { o.id = id; D[id] = o; };
  // — újkőkor
  T('weaving', { name: 'Szövés', era: 'neolithic', prereq: ['fiber_twisting', 'basket_weaving'], items: { fiber: 6 }, difficulty: 0.82, need: 'warmth', skill: 'crafting', minSkill: 0.45, recipes: ['cloth', 'wool_clothes'], fx: { warmth: 1 }, wow: 'Első szőtt vászon', desc: 'A rostból vászon lesz: könnyebb, melegebb ruha.' });
  T('carpentry', { name: 'Ácsmesterség', era: 'neolithic', prereq: ['woodworking', 'hut_construction'], items: { wood: 8 }, difficulty: 0.84, skill: 'building', minSkill: 0.5, buildings: ['workshop'], fx: { build: 0.15, wood: 0.1 }, wow: 'Első műhely', desc: 'Illesztett gerendák, szegek nélkül: műhely, amelyben jobb szerszám születik.' });
  T('granary_building', { name: 'Magtárépítés', era: 'neolithic', prereq: ['seed_planting', 'pottery'], items: { wood: 6, clay: 4 }, difficulty: 0.85, need: 'food', skill: 'building', minSkill: 0.5, buildings: ['granary'], fx: { preserve: 0.2 }, wow: 'Első magtár', desc: 'Egy közös, száraz raktár: a termés kitart tavaszig.' });
  T('well_digging', { name: 'Kútásás', era: 'neolithic', prereq: ['digging', 'stone_masonry'], items: { stone: 6 }, difficulty: 0.86, need: 'water', skill: 'building', minSkill: 0.55, buildings: ['well'], wow: 'Az első kútásás', desc: 'Víz a föld alól, ott, ahol az ember lakik.' });
  T('horticulture', { name: 'Gyümölcstermesztés', era: 'neolithic', prereq: ['seed_planting', 'foraging_lore'], items: { berries: 4, wood: 2 }, difficulty: 0.86, need: 'food', skill: 'farming', minSkill: 0.4, buildings: ['orchard'], fx: { food: 0.1 }, wow: 'Első gyümölcsös', desc: 'Az elültetett fa évről évre terem.' });
  T('animal_husbandry', { name: 'Állattartás', era: 'neolithic', prereq: ['spear_making', 'fiber_twisting'], items: { fiber: 6, wood: 6 }, difficulty: 0.9, need: 'food', skill: 'hunting', minSkill: 0.5, buildings: ['pasture'], fx: { hunt: 0.2 }, wow: 'Első karám', desc: 'A megszelídített vad nem szalad el: tej, gyapjú, hús a ház mellett.' });
  T('dairy', { name: 'Tejfeldolgozás', era: 'neolithic', prereq: ['animal_husbandry', 'pottery'], items: { milk: 2 }, difficulty: 0.8, need: 'food', skill: 'crafting', minSkill: 0.4, recipes: ['cheese'], desc: 'A tejből sajt lesz, ami hónapokig eláll.' });
  T('brewing', { name: 'Sörfőzés', era: 'neolithic', prereq: ['seed_planting', 'pottery'], items: { grain: 3 }, difficulty: 0.82, skill: 'crafting', minSkill: 0.4, recipes: ['beer'], accidents: [{ during: 'rest:fire', chance: 0.01, items: { grain: 3 } }], wow: 'Első sör', desc: 'A vízben hagyott gabona furcsa, vidám itallá erjed.' });
  T('plowing', { name: 'Ekehasználat', era: 'neolithic', prereq: ['seed_planting', 'woodworking'], items: { wood: 5 }, difficulty: 0.86, need: 'food', skill: 'farming', minSkill: 0.5, recipes: ['wooden_plow'], fx: { farm: 0.2 }, wow: 'Első eke', desc: 'A felszántott föld többet terem.' });
  T('kiln_building', { name: 'Kemenceépítés', era: 'neolithic', prereq: ['pottery', 'stone_masonry'], items: { clay: 8, stone: 6 }, difficulty: 0.87, skill: 'building', minSkill: 0.55, buildings: ['kiln'], wow: 'Első kemence', desc: 'A zárt kemence forróbb a tábortűznél: keményebb edény, égetett tégla.' });
  T('brick_making', { name: 'Téglavetés', era: 'neolithic', prereq: ['kiln_building'], items: { clay: 6 }, nearby: 'kiln', difficulty: 0.86, skill: 'building', minSkill: 0.55, recipes: ['brick'], buildings: ['brick_house'], wow: 'Első tégla', desc: 'Kiégetett agyagtégla: gyorsabb és szárazabb falak, mint kőből.' });
  T('ritual', { name: 'Szertartás', era: 'neolithic', prereq: [], items: { stone: 4 }, difficulty: 0.8, skill: 'social', minSkill: 0.3, minPop: 4, buildings: ['shrine'], wow: 'Az első szertartás', desc: 'Kövek, tűz, közös ének a halottakért és az égi hangért. A félelem szertartásba rendeződik.' });
  T('counting', { name: 'Számolás', era: 'neolithic', prereq: ['granary_building'], items: {}, difficulty: 0.84, skill: 'crafting', minSkill: 0.4, minPop: 5, boosts: { writing: 0.1 }, desc: 'Rovások a boton: mennyi gabona, hány nap, hány ember.' });
  T('tribal_council', { name: 'Törzsi tanács', era: 'neolithic', prereq: ['ritual'], items: {}, difficulty: 0.82, skill: 'social', minSkill: 0.45, minPop: 6, fx: { teach: 0.1 }, wow: 'Az első tanács', desc: 'A vének és a legerősebbek szava dönt: a csoportnak vezetője lesz.' });
  T('archery', { name: 'Íjászat', era: 'neolithic', prereq: ['spear_making', 'fiber_twisting'], items: { wood: 2, fiber: 3 }, difficulty: 0.84, need: 'food', skill: 'hunting', minSkill: 0.45, recipes: ['bow'], fx: { hunt: 0.25 }, wow: 'Első íj', desc: 'A feszített ág messzebbre visz, mint a kar.' });
  // — rézkor
  T('charcoal_making', { name: 'Szénégetés', era: 'copper', prereq: ['fire_making', 'kiln_building'], items: { wood: 6 }, nearby: 'fire', difficulty: 0.85, skill: 'crafting', minSkill: 0.5, recipes: ['charcoal'], accidents: [{ during: 'rest:fire', chance: 0.005, items: { wood: 4 } }], desc: 'A lassan, levegő nélkül égő fa forróbb tüzet ad.' });
  T('copper_smelting', { name: 'Rézolvasztás', era: 'copper', prereq: ['ore_lore_copper', 'charcoal_making', 'kiln_building'], items: { ore_copper: 3, charcoal: 2 }, nearby: 'kiln', difficulty: 0.9, skill: 'crafting', minSkill: 0.6, minPop: 4, buildings: ['furnace'], recipes: ['copper'], wow: 'Az első fém', desc: 'A zöld kőből a kemence forróságában vörös fém csorog.' });
  T('copper_tools', { name: 'Rézszerszámok', era: 'copper', prereq: ['copper_smelting'], items: { copper: 2, wood: 1 }, nearby: 'furnace', difficulty: 0.85, skill: 'crafting', minSkill: 0.6, recipes: ['copper_axe'], fx: { wood: 0.2 }, wow: 'Első rézbalta', desc: 'A fém él tovább tart, mint a kő.' });
  T('mining', { name: 'Bányászat', era: 'copper', prereq: ['copper_tools', 'digging'], items: { copper: 2, wood: 2 }, difficulty: 0.86, skill: 'gathering', minSkill: 0.55, recipes: ['pickaxe'], fx: { mine: 0.4 }, wow: 'Első bánya', desc: 'Csákánnyal a föld mélyebb rétegei is megnyílnak.' });
  // — bronzkor
  T('bronze_alloy', { name: 'Bronzötvözés', era: 'bronze', prereq: ['copper_smelting', 'ore_lore_tin'], items: { copper: 2, ore_tin: 2, charcoal: 2 }, nearby: 'furnace', difficulty: 0.92, skill: 'crafting', minSkill: 0.65, minPop: 5, recipes: ['tin', 'bronze'], wow: 'Az első bronz', desc: 'Réz és ón együtt keményebb, mint bármelyik külön.' });
  T('bronze_tools', { name: 'Bronzművesség', era: 'bronze', prereq: ['bronze_alloy'], items: { bronze: 2, wood: 2 }, nearby: 'furnace', difficulty: 0.88, skill: 'crafting', minSkill: 0.65, recipes: ['bronze_axe', 'bronze_spear', 'bronze_plow'], fx: { wood: 0.2, hunt: 0.2, farm: 0.15 }, wow: 'Első bronzszerszám', desc: 'Balta, lándzsa, eke bronzból: a munka felgyorsul.' });
  T('writing', { name: 'Írás', era: 'bronze', prereq: ['counting', 'pottery'], items: { clay: 4 }, difficulty: 0.93, skill: 'crafting', minSkill: 0.6, minPop: 6, buildings: ['archive'], fx: { teach: 0.15 }, wow: 'Az első írás', desc: 'Jelek az agyagban, amelyek megőrzik a tudást akkor is, ha a tudó meghal.' });
  T('trade', { name: 'Kereskedelem', era: 'bronze', prereq: ['counting', 'tribal_council'], items: { cloth: 2 }, difficulty: 0.88, skill: 'social', minSkill: 0.5, minPop: 8, buildings: ['market'], fx: { food: 0.1 }, wow: 'Az első piac', desc: 'Ami az egyiknek felesleg, a másiknak hiány: a csere mindkettőt gazdagítja.' });
  T('irrigation', { name: 'Öntözés', era: 'bronze', prereq: ['well_digging', 'plowing'], items: { stone: 8 }, nearby: 'water', difficulty: 0.9, need: 'food', skill: 'building', minSkill: 0.6, minPop: 8, buildings: ['irrigation'], fx: { farm: 0.3 }, wow: 'Első öntözőcsatorna', desc: 'A vizet a földre vezetni: aszályban is terem.' });
  T('organized_religion', { name: 'Szervezett vallás', era: 'bronze', prereq: ['ritual', 'writing', 'tribal_council'], items: { stone: 6 }, difficulty: 0.9, skill: 'social', minSkill: 0.55, minPop: 12, buildings: ['temple'], fx: { teach: 0.1 }, wow: 'Az első templom', desc: 'Papok, szent szövegek, ünnepek: a hit intézménnyé válik.' });
  T('sailing', { name: 'Hajózás', era: 'bronze', prereq: ['carpentry', 'weaving', 'fishing'], items: { wood: 10, cloth: 2 }, nearby: 'water', difficulty: 0.9, skill: 'building', minSkill: 0.6, buildings: ['harbor'], fx: { food: 0.1, speed: 0.05 }, wow: 'Az első hajó', desc: 'Vászon a szélben: a víz többé nem határ.' });
  T('calendar', { name: 'Naptár', era: 'bronze', prereq: ['counting', 'ritual'], items: {}, difficulty: 0.88, skill: 'farming', minSkill: 0.5, fx: { farm: 0.1 }, boosts: { astronomy: 0.1 }, desc: 'A csillagok járásából tudni, mikor kell vetni.' });
  T('tailoring', { name: 'Szabóság', era: 'bronze', prereq: ['weaving', 'hide_working', 'carpentry'], items: { cloth: 2, hide: 1 }, nearby: 'workshop', difficulty: 0.85, need: 'warmth', skill: 'crafting', minSkill: 0.6, recipes: ['coat'], fx: { warmth: 1 }, desc: 'Szabott, varrott kabát a tél ellen.' });
  T('fortification', { name: 'Palánképítés', era: 'neolithic', prereq: ['hut_construction', 'tribal_council'], items: { wood: 10 }, difficulty: 0.86, need: 'safety', skill: 'building', minSkill: 0.5, minPop: 5, buildings: ['palisade'], wow: 'Az első palánk', desc: 'Hegyezett cölöpök a tábor körül: a vad és az idegen kint marad.' });
  T('stone_walls', { name: 'Kőfalak', era: 'bronze', prereq: ['fortification', 'stone_masonry'], items: { stone: 16 }, difficulty: 0.9, need: 'safety', skill: 'building', minSkill: 0.65, minPop: 10, buildings: ['stone_wall'], wow: 'Az első kőfal', desc: 'Fal, amelyet tűz nem éget és kar nem dönt.' });
  T('dyeing', { name: 'Kelmefestés', era: 'bronze', prereq: ['weaving', 'herbal_medicine'], items: { cloth: 2, berries: 4 }, difficulty: 0.84, skill: 'crafting', minSkill: 0.5, wow: 'Az első festett ruha', desc: 'Növényből és földből szín: a ruha többé nem csak melegít, hanem beszél is arról, ki viseli.' });
  T('boatbuilding', { name: 'Csónaképítés', era: 'neolithic', prereq: ['woodworking', 'fishing'], items: { wood: 8, fiber: 4 }, nearby: 'water', difficulty: 0.84, need: 'food', skill: 'building', minSkill: 0.45, recipes: ['boat'], fx: { food: 0.1 }, wow: 'Az első csónak', desc: 'Kivájt törzs a vízen: a hal ott is elérhető, ahová a part nem ér.' });
  // — vaskor
  T('iron_smelting', { name: 'Vasolvasztás', era: 'iron', prereq: ['charcoal_making', 'kiln_building', 'ore_lore_iron'], boosts: { bronze_alloy: 0.15, copper_smelting: 0.1 }, items: { ore_iron: 3, charcoal: 3 }, nearby: 'kiln', difficulty: 0.95, skill: 'crafting', minSkill: 0.7, minPop: 8, recipes: ['iron'], wow: 'Az első vas', desc: 'A vörös kő makacsabb a réznél, de a fémje keményebb.' });
  T('iron_working', { name: 'Kovácsolás', era: 'iron', prereq: ['iron_smelting', 'carpentry'], items: { iron: 3, wood: 4 }, difficulty: 0.92, skill: 'crafting', minSkill: 0.7, minPop: 8, buildings: ['forge'], recipes: ['iron_axe', 'iron_spear', 'iron_pickaxe', 'iron_plow'], fx: { wood: 0.3, hunt: 0.2, farm: 0.2, mine: 0.3, build: 0.15 }, wow: 'Az első kovács', desc: 'Izzó vas az üllőn: minden szerszám újjászületik.' });
  T('alphabet', { name: 'Ábécé', era: 'iron', prereq: ['writing'], items: { clay: 2 }, nearby: 'archive', difficulty: 0.9, skill: 'social', minSkill: 0.55, minPop: 10, fx: { teach: 0.25 }, boosts: { schooling: 0.1 }, desc: 'Kevés jel, amit bárki megtanulhat: az írás a sokaké lesz.' });
  T('coinage', { name: 'Pénzverés', era: 'iron', prereq: ['trade', 'copper_smelting'], itemsAny: [{ gold_nugget: 1 }, { copper: 2 }], nearby: 'workshop', difficulty: 0.9, skill: 'crafting', minSkill: 0.6, minPop: 12, recipes: ['coin'], fx: { food: 0.1 }, wow: 'Az első érme', desc: 'Egy darab csillogó fém, amit mindenki elfogad. A csere elszakad a pillanattól.' });
  T('road_building', { name: 'Útépítés', era: 'iron', prereq: ['stone_masonry', 'tribal_council'], items: { stone: 12 }, difficulty: 0.88, skill: 'building', minSkill: 0.6, minPop: 10, fx: { speed: 0.15 }, wow: 'Az első út', desc: 'Kővel rakott út: a szekér nem süllyed a sárba.' });
  T('medicine', { name: 'Gyógyítás', era: 'iron', prereq: ['herbal_medicine', 'writing'], items: { fiber: 4, berries: 4 }, difficulty: 0.9, skill: 'medicine', minSkill: 0.5, minPop: 8, fx: { health: 0.2 }, wow: 'Az első orvos', desc: 'A sebek tisztítása, a láz feljegyzett kezelése: kevesebben halnak meg feleslegesen.' });
  T('milling', { name: 'Őrlés', era: 'iron', prereq: ['plowing', 'carpentry'], items: { wood: 10, stone: 6 }, difficulty: 0.88, need: 'food', skill: 'building', minSkill: 0.6, minPop: 8, buildings: ['mill'], recipes: ['flour'], fx: { food: 0.1 }, wow: 'Az első malom', desc: 'A víz vagy a szél forgatja a követ, ami a gabonát liszté őrli.' });
  T('baking', { name: 'Sütés', era: 'iron', prereq: ['milling', 'kiln_building'], items: { flour: 1 }, nearby: 'fire', difficulty: 0.8, need: 'food', skill: 'crafting', minSkill: 0.45, recipes: ['bread'], fx: { food: 0.1 }, wow: 'Az első kenyér', desc: 'A lisztből kelt, sült kenyér: laktató, elálló.' });
  T('law_code', { name: 'Törvények', era: 'iron', prereq: ['writing', 'tribal_council'], items: {}, nearby: 'archive', difficulty: 0.9, skill: 'social', minSkill: 0.6, minPop: 15, fx: { teach: 0.1 }, wow: 'Az első törvény', desc: 'Leírt szabályok, amelyek a vezető fölött is állnak.' });
  // — ókor
  T('architecture', { name: 'Építészet', era: 'classical', prereq: ['brick_making', 'road_building', 'counting'], items: { brick: 10, stone: 10 }, difficulty: 0.92, skill: 'building', minSkill: 0.7, minPop: 15, buildings: ['town_house'], fx: { build: 0.2 }, wow: 'Az első boltív', desc: 'Boltív, oszlop, emelet: házak, amelyek a dédunokákat is látják.' });
  T('glassmaking', { name: 'Üvegfúvás', era: 'classical', prereq: ['kiln_building', 'charcoal_making'], items: { stone: 4, charcoal: 2 }, nearby: 'furnace', difficulty: 0.9, skill: 'crafting', minSkill: 0.65, minPop: 10, recipes: ['glass'], wow: 'Az első üveg', desc: 'A megolvadt homok átlátszó, kemény anyaggá dermed.' });
  T('schooling', { name: 'Iskola', era: 'classical', prereq: ['alphabet', 'law_code'], items: { wood: 6 }, nearby: 'archive', difficulty: 0.9, skill: 'social', minSkill: 0.6, minPop: 12, buildings: ['school'], fx: { teach: 0.3 }, wow: 'Az első iskola', desc: 'A gyerekek nem csak a szüleiktől tanulnak.' });
  T('mathematics', { name: 'Matematika', era: 'classical', prereq: ['counting', 'alphabet', 'calendar'], items: {}, nearby: 'archive', difficulty: 0.93, skill: 'crafting', minSkill: 0.6, minPop: 15, fx: { discovery: 0.1, build: 0.1 }, boosts: { mechanics: 0.1, astronomy: 0.1 }, desc: 'A számok és formák szabályai, amelyek mindenre érvényesek.' });
  T('astronomy', { name: 'Csillagászat', era: 'classical', prereq: ['calendar', 'mathematics'], items: {}, difficulty: 0.92, skill: 'exploring', minSkill: 0.5, minPop: 12, fx: { speed: 0.05 }, boosts: { navigation: 0.15, scientific_method: 0.1 }, desc: 'Az égbolt rendje: a világ nagyobb, mint amit a szem lát.' });
  T('steel_making', { name: 'Acélgyártás', era: 'classical', prereq: ['iron_working', 'ore_lore_coal'], items: { iron: 3, coal: 2 }, nearby: 'forge', difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 15, recipes: ['steel', 'steel_axe'], fx: { wood: 0.2, build: 0.1, mine: 0.2 }, wow: 'Az első acél', desc: 'Szénnel edzett vas: rugalmas és kemény egyszerre.' });
  T('mechanics', { name: 'Gépezetek', era: 'classical', prereq: ['milling', 'mathematics', 'iron_working'], items: { iron: 2, wood: 4 }, nearby: 'workshop', difficulty: 0.93, skill: 'crafting', minSkill: 0.7, minPop: 15, recipes: ['machine_part'], fx: { craft: 0.2, build: 0.1 }, wow: 'Az első gép', desc: 'Fogaskerék, csiga, emelő: az erő megsokszorozható.' });
  T('castles', { name: 'Várépítés', era: 'medieval', prereq: ['stone_walls', 'architecture', 'law_code'], items: { stone: 30, brick: 10 }, difficulty: 0.93, need: 'safety', skill: 'building', minSkill: 0.75, minPop: 20, buildings: ['castle'], wow: 'Az első vár', desc: 'Tornyok, kapu, falak: a hatalom kőbe zárva.' });
  // — középkor
  T('paper_making', { name: 'Papírkészítés', era: 'medieval', prereq: ['weaving', 'writing', 'carpentry'], items: { fiber: 6, wood: 2 }, nearby: 'workshop', difficulty: 0.9, skill: 'crafting', minSkill: 0.65, minPop: 12, recipes: ['paper'], buildings: ['library'], fx: { teach: 0.2 }, wow: 'Az első papír', desc: 'Rostból préselt vékony lap: könnyű, olcsó, tele lehet írni.' });
  T('crop_rotation', { name: 'Vetésforgó', era: 'medieval', prereq: ['plowing', 'writing'], items: {}, difficulty: 0.88, need: 'food', skill: 'farming', minSkill: 0.65, minPop: 10, fx: { farm: 0.3 }, desc: 'A föld pihen, ha váltogatják, mit vetnek belé.' });
  T('navigation', { name: 'Hajózási tudomány', era: 'medieval', prereq: ['sailing', 'astronomy'], items: { iron: 1 }, difficulty: 0.92, skill: 'exploring', minSkill: 0.6, minPop: 12, fx: { speed: 0.1, food: 0.05 }, wow: 'Az első iránytű', desc: 'Iránytű és csillagtérkép: a nyílt vízen is tudni, merre.' });
  T('concrete', { name: 'Beton', era: 'medieval', prereq: ['architecture', 'kiln_building'], items: { stone: 6, clay: 3 }, nearby: 'kiln', difficulty: 0.9, skill: 'building', minSkill: 0.7, minPop: 15, recipes: ['concrete'], fx: { build: 0.15 }, desc: 'Égetett kő és víz, amely maga is kővé áll össze.' });
  T('mechanical_clock', { name: 'Óra', era: 'medieval', prereq: ['mechanics', 'astronomy'], items: { machine_part: 2 }, nearby: 'workshop', difficulty: 0.93, skill: 'crafting', minSkill: 0.75, minPop: 15, fx: { craft: 0.1, discovery: 0.05 }, desc: 'A napot egyenlő darabokra vágó szerkezet.' });
  T('gunpowder', { name: 'Lőpor', era: 'medieval', prereq: ['charcoal_making', 'ore_lore_coal', 'mathematics'], itemsAny: [{ charcoal: 3, salt: 1 }, { charcoal: 3, coal: 2 }], difficulty: 0.94, skill: 'crafting', minSkill: 0.7, minPop: 15, accidents: [{ during: 'craft:charcoal', chance: 0.002, items: { salt: 1 } }], fx: { mine: 0.3 }, boosts: { firearms: 0.15 }, wow: 'Az első robbanás', desc: 'Szén, kén, salétrom: por, amely egy szikrától mennydörög.' });
  T('optics', { name: 'Optika', era: 'medieval', prereq: ['glassmaking', 'mathematics'], items: { glass: 2 }, nearby: 'workshop', difficulty: 0.92, skill: 'crafting', minSkill: 0.7, minPop: 12, fx: { discovery: 0.1 }, boosts: { astronomy: 0.2, anatomy: 0.1 }, desc: 'Csiszolt üveg, amely a kicsit naggyá, a távolit közelivé teszi.' });
  T('universities', { name: 'Egyetem', era: 'medieval', prereq: ['schooling', 'paper_making', 'mathematics'], items: { paper: 4 }, nearby: 'library', difficulty: 0.93, skill: 'social', minSkill: 0.7, minPop: 21, buildings: ['university'], fx: { discovery: 0.2, teach: 0.3 }, wow: 'Az első egyetem', desc: 'Egy hely, ahol a tudás maga a munka.' });
  // — reneszánsz
  T('printing', { name: 'Könyvnyomtatás', era: 'renaissance', prereq: ['paper_making', 'mechanics', 'alphabet'], items: { machine_part: 2, paper: 4 }, nearby: 'workshop', difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 15, recipes: ['book'], buildings: ['printing_house'], fx: { teach: 0.5, discovery: 0.1 }, wow: 'Az első nyomtatott könyv', desc: 'Mozgatható betűk: egy gondolat ezer példányban.' });
  T('scientific_method', { name: 'Tudományos módszer', era: 'renaissance', prereq: ['universities', 'optics', 'printing'], items: { glass: 2, paper: 2 }, nearby: 'university', difficulty: 0.95, skill: 'crafting', minSkill: 0.75, minPop: 18, buildings: ['lab'], fx: { discovery: 0.5 }, wow: 'Az első kísérlet, amit leírtak', desc: 'Kérdés, mérés, ismétlés, kétely: a tudás rendszerré válik.' });
  T('anatomy', { name: 'Anatómia', era: 'renaissance', prereq: ['medicine', 'optics', 'universities'], items: { paper: 2 }, nearby: 'university', difficulty: 0.93, skill: 'medicine', minSkill: 0.65, minPop: 15, fx: { health: 0.2 }, desc: 'A test térképe.' });
  T('banking', { name: 'Bankügy', era: 'renaissance', prereq: ['coinage', 'mathematics', 'law_code'], items: { coin: 6, paper: 2 }, difficulty: 0.92, skill: 'social', minSkill: 0.7, minPop: 18, fx: { food: 0.1, build: 0.1 }, desc: 'Pénz, ami pénzt csinál: a jövő beruházhatóvá válik.' });
  T('firearms', { name: 'Lőfegyver', era: 'renaissance', prereq: ['gunpowder', 'steel_making', 'mechanics'], items: { steel: 2, machine_part: 1 }, nearby: 'workshop', difficulty: 0.94, skill: 'crafting', minSkill: 0.75, minPop: 15, recipes: ['rifle'], fx: { hunt: 0.4 }, wow: 'Az első lövés', desc: 'Cső, kő, por: az erő elszakad az izomtól.' });
  T('chemistry', { name: 'Kémia', era: 'renaissance', prereq: ['scientific_method', 'glassmaking'], items: { glass: 3, salt: 1 }, nearby: 'lab', difficulty: 0.95, skill: 'crafting', minSkill: 0.75, minPop: 18, fx: { discovery: 0.15 }, boosts: { pharmacology: 0.15, oil_refining: 0.1, plastics: 0.1 }, desc: 'Az anyagok titkos nyelvtana.' });
  // — ipari kor
  T('steam_engine', { name: 'Gőzgép', era: 'industrial', prereq: ['mechanics', 'steel_making', 'ore_lore_coal', 'scientific_method'], items: { steel: 3, machine_part: 3, coal: 2 }, nearby: 'lab', difficulty: 0.96, skill: 'crafting', minSkill: 0.8, minPop: 24, fx: { craft: 0.4, mine: 0.4, speed: 0.1 }, wow: 'Az első gép, amely magától jár', desc: 'Forró gőz, amely dugattyút tol: az erő többé nem izomból és szélből jön.' });
  T('factory_system', { name: 'Gyáripar', era: 'industrial', prereq: ['steam_engine', 'trade'], boosts: { banking: 0.1 }, items: { machine_part: 6, brick: 10 }, difficulty: 0.95, skill: 'building', minSkill: 0.8, minPop: 28, buildings: ['factory'], fx: { craft: 0.6 }, wow: 'Az első gyár', desc: 'Sok kéz, egy gép, egy tető alatt: a termelés megsokszorozódik.' });
  T('railway', { name: 'Vasút', era: 'industrial', prereq: ['steam_engine', 'road_building'], items: { steel: 6, wood: 6 }, difficulty: 0.95, skill: 'building', minSkill: 0.8, minPop: 28, fx: { speed: 0.3, food: 0.1 }, wow: 'Az első vonat', desc: 'Sínen futó gőz: a távolság összemegy.' });
  T('machine_tools', { name: 'Szerszámgépek', era: 'industrial', prereq: ['factory_system'], items: { steel: 4, machine_part: 4 }, nearby: 'factory', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 28, recipes: ['drill'], fx: { craft: 0.3, mine: 0.4 }, desc: 'Gépek, amelyek gépeket csinálnak.' });
  T('sanitation', { name: 'Közegészségügy', era: 'industrial', prereq: ['medicine', 'concrete', 'law_code'], items: { concrete: 6 }, difficulty: 0.93, skill: 'building', minSkill: 0.75, minPop: 28, fx: { health: 0.3 }, wow: 'Az első csatorna', desc: 'Tiszta víz be, szenny ki: a járványok megritkulnak.' });
  T('vaccination', { name: 'Oltás', era: 'industrial', prereq: ['anatomy', 'chemistry'], items: { glass: 2, medicine: 1 }, nearby: 'lab', difficulty: 0.95, skill: 'medicine', minSkill: 0.75, minPop: 24, fx: { health: 0.3 }, wow: 'Az első oltás', desc: 'A gyenge kórral megtanított test a valódit is legyőzi.' });
  T('pharmacology', { name: 'Gyógyszertan', era: 'industrial', prereq: ['chemistry', 'anatomy'], items: { glass: 2, berries: 4 }, nearby: 'lab', difficulty: 0.94, skill: 'medicine', minSkill: 0.7, minPop: 21, recipes: ['medicine'], fx: { health: 0.2 }, desc: 'Mért, tiszta hatóanyag a gyógynövény helyett.' });
  T('electricity', { name: 'Elektromosság', era: 'industrial', prereq: ['scientific_method', 'copper_smelting', 'mechanics', 'chemistry'], items: { copper: 4, iron: 2 }, nearby: 'lab', difficulty: 0.96, skill: 'crafting', minSkill: 0.8, minPop: 28, recipes: ['electric_part'], fx: { discovery: 0.2 }, wow: 'Az első szikra a drótban', desc: 'Láthatatlan erő a rézben, amely fényt, hőt és mozgást ad.' });
  T('telegraph', { name: 'Távíró', era: 'industrial', prereq: ['electricity', 'alphabet'], items: { electric_part: 2, copper: 4 }, nearby: 'workshop', difficulty: 0.94, skill: 'crafting', minSkill: 0.8, minPop: 28, fx: { teach: 0.3 }, wow: 'Az első üzenet a dróton', desc: 'Szavak, amelyek gyorsabbak a lónál.' });
  T('oil_drilling', { name: 'Olajfúrás', era: 'industrial', prereq: ['machine_tools', 'steam_engine'], items: { steel: 4, machine_part: 2 }, difficulty: 0.94, skill: 'gathering', minSkill: 0.7, minPop: 28, fx: { mine: 0.2 }, wow: 'Az első olajkút', desc: 'Fekete, égő folyadék a mélyből.' });
  T('oil_refining', { name: 'Olajfinomítás', era: 'industrial', prereq: ['oil_drilling', 'chemistry'], items: { oil: 3 }, nearby: 'factory', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 31, recipes: ['fuel'], desc: 'A nyersolajból üzemanyag válik el.' });
  T('automobile', { name: 'Gépkocsi', era: 'modern', prereq: ['internal_combustion', 'road_building', 'steel_making'], items: { steel: 6, machine_part: 4, fuel: 2 }, nearby: 'factory', difficulty: 0.96, skill: 'crafting', minSkill: 0.85, minPop: 35, recipes: ['car'], fx: { speed: 0.5 }, wow: 'Az első gépkocsi', desc: 'Négy kerék és egy motor: a távolság elveszti a jelentését.' });
  // — modern kor
  T('electrification', { name: 'Villamosítás', era: 'modern', prereq: ['electricity', 'factory_system', 'concrete'], items: { electric_part: 6, steel: 4, concrete: 6 }, nearby: 'factory', difficulty: 0.96, skill: 'building', minSkill: 0.85, minPop: 35, buildings: ['power_plant', 'modern_house'], fx: { craft: 0.4, warmth: 3, discovery: 0.2 }, wow: 'Az első villanyfény az éjszakában', desc: 'Erőmű, vezeték, izzó: az éjszaka véget ér.' });
  T('internal_combustion', { name: 'Belső égésű motor', era: 'modern', prereq: ['oil_refining', 'machine_tools'], items: { steel: 4, machine_part: 4, fuel: 2 }, nearby: 'factory', difficulty: 0.96, skill: 'crafting', minSkill: 0.85, minPop: 35, recipes: ['chainsaw', 'tractor'], fx: { speed: 0.4, farm: 0.4, wood: 0.4 }, wow: 'Az első motor', desc: 'Robbanások sora egy fémdobozban: erő, ami magával vihető.' });
  T('radio', { name: 'Rádió', era: 'modern', prereq: ['telegraph', 'electrification'], items: { electric_part: 4, glass: 2 }, nearby: 'lab', difficulty: 0.95, skill: 'crafting', minSkill: 0.85, minPop: 35, fx: { teach: 0.4 }, wow: 'Az első hang a levegőből', desc: 'Láthatatlan hullámok, amelyek hangot hordoznak.' });
  T('modern_medicine', { name: 'Modern orvoslás', era: 'modern', prereq: ['vaccination', 'pharmacology', 'sanitation'], items: { medicine: 4, glass: 4 }, nearby: 'lab', difficulty: 0.96, skill: 'medicine', minSkill: 0.85, minPop: 35, buildings: ['hospital'], fx: { health: 0.5 }, wow: 'Az első kórház', desc: 'Antibiotikum, műtét, kórház: a betegség többé nem ítélet.' });
  T('aviation', { name: 'Repülés', era: 'modern', prereq: ['internal_combustion', 'mathematics'], items: { steel: 6, machine_part: 6, fuel: 3, cloth: 4 }, nearby: 'factory', difficulty: 0.97, skill: 'crafting', minSkill: 0.85, minPop: 42, fx: { speed: 0.3 }, wow: 'Az első repülés', desc: 'Az ember az ég felé, ahonnan a hang jött.' });
  T('plastics', { name: 'Műanyagok', era: 'modern', prereq: ['oil_refining', 'chemistry'], items: { oil: 3, glass: 1 }, nearby: 'lab', difficulty: 0.95, skill: 'crafting', minSkill: 0.8, minPop: 35, recipes: ['plastic'], fx: { craft: 0.2 }, desc: 'Olajból formázható, könnyű, örök anyag.' });
  T('nuclear_fission', { name: 'Maghasadás', era: 'modern', prereq: ['electrification', 'chemistry', 'mathematics'], items: { steel: 6, electric_part: 6, concrete: 10 }, nearby: 'lab', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 56, fx: { craft: 0.3, discovery: 0.2 }, wow: 'Az atom felnyitása', desc: 'Az anyag legmélyén rejtett erő — áldás és átok.' });
  T('rocketry', { name: 'Rakétatechnika', era: 'modern', prereq: ['aviation', 'chemistry', 'nuclear_fission'], items: { steel: 10, fuel: 6, electric_part: 6 }, nearby: 'lab', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 63, fx: { discovery: 0.1 }, wow: 'Az első rakéta', desc: 'Tűz, amely az ég fölé visz.' });
  // — digitális kor
  T('transistor', { name: 'Tranzisztor', era: 'digital', prereq: ['electrification', 'chemistry', 'radio'], items: { electric_part: 4, glass: 2 }, nearby: 'lab', difficulty: 0.97, skill: 'crafting', minSkill: 0.9, minPop: 49, fx: { discovery: 0.2 }, wow: 'Az első kapcsoló, amelynek nincs mozgó része', desc: 'Egy morzsa kristály, amely igent és nemet mond.' });
  T('integrated_circuit', { name: 'Integrált áramkör', era: 'digital', prereq: ['transistor', 'optics'], items: { electric_part: 4, glass: 4, copper: 2 }, nearby: 'lab', difficulty: 0.97, skill: 'crafting', minSkill: 0.9, minPop: 56, recipes: ['chip'], fx: { craft: 0.3 }, wow: 'Az első csip', desc: 'Ezer kapcsoló egy körömnyi lapon.' });
  T('computer', { name: 'Számítógép', era: 'digital', prereq: ['integrated_circuit', 'mathematics', 'electrification'], items: { chip: 6, electric_part: 6, plastic: 2 }, nearby: 'lab', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 63, buildings: ['computer_center'], fx: { discovery: 0.5, teach: 0.3 }, wow: 'Az első számítógép', desc: 'Gép, amely gondolatokat számol. Az emberek elkezdik megkérdezni tőle, amit egykor a hangtól.' });
  T('software', { name: 'Szoftver', era: 'digital', prereq: ['computer', 'alphabet'], items: { chip: 2, paper: 2 }, nearby: 'computer_center', difficulty: 0.96, skill: 'crafting', minSkill: 0.9, minPop: 63, fx: { discovery: 0.3, craft: 0.2 }, desc: 'Utasítások, amelyek nem anyagból vannak, mégis mozgatják az anyagot.' });
  T('internet', { name: 'Hálózat', era: 'digital', prereq: ['software', 'telegraph', 'radio'], items: { chip: 10, electric_part: 10, copper: 10 }, nearby: 'computer_center', difficulty: 0.98, skill: 'crafting', minSkill: 0.9, minPop: 84, buildings: ['data_center'], fx: { teach: 1.0, discovery: 0.4 }, wow: 'Az első hálózat', desc: 'Minden gép beszél minden géppel: a tudás egy helyen van, mindenhol.' });
  T('genetics', { name: 'Genetika', era: 'digital', prereq: ['modern_medicine', 'computer', 'chemistry'], items: { medicine: 4, chip: 4, glass: 4 }, nearby: 'lab', difficulty: 0.98, skill: 'medicine', minSkill: 0.9, minPop: 70, fx: { health: 0.4, farm: 0.3 }, wow: 'A saját kódjuk olvasása', desc: 'Az élet írása, amit most már ők is olvasnak.' });
  T('spaceflight', { name: 'Űrrepülés', era: 'digital', prereq: ['rocketry', 'computer'], items: { steel: 20, fuel: 10, chip: 10, electric_part: 10 }, nearby: 'computer_center', difficulty: 0.985, skill: 'crafting', minSkill: 0.92, minPop: 105, fx: { discovery: 0.3 }, wow: 'Az első ember az űrben', desc: 'A vidék, aztán a világ, aztán az ég: kimennek megnézni, mi van a peremen túl.' });
  // — MI-kor
  T('machine_learning', { name: 'Gépi tanulás', era: 'ai', prereq: ['software', 'internet', 'mathematics'], items: { chip: 20, electric_part: 6 }, nearby: 'data_center', difficulty: 0.985, skill: 'crafting', minSkill: 0.92, minPop: 105, fx: { discovery: 0.6, teach: 0.5 }, wow: 'Az első gép, amely tanul', desc: 'A gép nem utasítást kap, hanem példát — és magától jön rá a szabályra.' });
  T('artificial_intelligence', { name: 'Mesterséges intelligencia', era: 'ai', prereq: ['machine_learning', 'genetics'], items: { chip: 40, electric_part: 10 }, nearby: 'data_center', difficulty: 0.99, skill: 'crafting', minSkill: 0.95, minPop: 140, fx: { discovery: 1.0, teach: 1.0, craft: 0.5, health: 0.3 }, wow: 'Az első elme, amelyet ők teremtettek', desc: 'Egy gondolkodó, amit nem szültek: ők lettek teremtők.' });
  T('fusion', { name: 'Magfúzió', era: 'ai', prereq: ['nuclear_fission', 'artificial_intelligence'], items: { steel: 20, chip: 20, concrete: 20 }, nearby: 'lab', difficulty: 0.99, skill: 'crafting', minSkill: 0.95, minPop: 140, fx: { craft: 0.6, warmth: 4 }, wow: 'Egy csillag a földön', desc: 'A nap ereje, egy palackban.' });
  T('world_simulation', { name: 'Világszimuláció', era: 'ai', prereq: ['artificial_intelligence', 'fusion', 'spaceflight'], items: { chip: 100, electric_part: 40, concrete: 40 }, nearby: 'data_center', difficulty: 0.995, skill: 'crafting', minSkill: 0.95, minPop: 175, buildings: ['simulation_core'], fx: { discovery: 1.0 }, wow: 'A világ a világban', desc: 'Egy gép, amelyben apró lények élnek, tanulnak és egy hangot hallanak az égből. Ők is Teremtők lettek.' });

  // ---------------------------------------------------------------- hatások, korszakok, szerszámok
  const FX_KEYS = ['food', 'hunt', 'wood', 'stone', 'mine', 'farm', 'build', 'craft', 'speed', 'discovery', 'teach', 'warmth', 'health', 'preserve'];
  const Tree = {
    ERAS, ERA_INDEX, FX_KEYS,
    /** A legjobb szerszám egy adott célra (balta, vadászfegyver, eke, csákány, ruha). */
    bestTool(a, slot) { let best = 0; for (const k in a.inv) { const it = I[k]; if (it && it.slot === slot && a.inv[k] > 0 && it.tier > best) best = it.tier; } return best; },
    /** Egy ember összesített szorzói a tudásából és szerszámaiból (naponta újraszámolva, gyorsítótárazva). */
    fx(world, a) {
      if (a._fx && a._fxTick === (world.tick / TPD | 0) && a._fxN === a.knowledge.techs.size) return a._fx;
      const f = {}; for (const k of FX_KEYS) f[k] = 0;
      for (const id of a.knowledge.techs) { const d = D[id]; if (d && d.fx) for (const k in d.fx) f[k] = (f[k] || 0) + d.fx[k]; }
      f.wood += this.bestTool(a, 'axe') * 0.25; f.hunt += this.bestTool(a, 'hunt') * 0.25; f.farm += this.bestTool(a, 'plow') * 0.25; f.mine += this.bestTool(a, 'mine') * 0.3; f.stone += this.bestTool(a, 'mine') * 0.2; f.food += this.bestTool(a, 'boat') * 0.15; f.speed += this.bestTool(a, 'vehicle') * 0.5;
      a._fx = f; a._fxTick = world.tick / TPD | 0; a._fxN = a.knowledge.techs.size; return f;
    },
    mult(world, a, key) { return 1 + (this.fx(world, a)[key] || 0); },
    /** Közös raktár a közelben, amelyben van a keresett anyagból (műhely, kovács, piac, gyár…). */
    publicStore(world, a, item, radius) { const list = this.storesNear(world, a, radius || 20); for (const b of list) if ((b.storage[item] || 0) > 0) return b; return null; },
    /** A közeli közös raktárak listája, naponta egyszer összegyűjtve emberenként (a sűrű városban ezreket kérdeznének). */
    storesNear(world, a, radius) { const day = world.tick / TPD | 0; if (a._psDay === day && a._psR === radius && a._ps) return a._ps; const out = []; for (const b of world.buildingsNear(a.x | 0, a.y | 0, radius)) { const d = B[b.kind]; if (b.progress >= 1 && d && d.public && d.storage && b.storage) out.push(b); } a._ps = out; a._psDay = day; a._psR = radius; return out; },
    /** Legközelebbi közös raktár, ahová termelni lehet. */
    nearestStore(world, a, radius) { let best = null, bd = 1e9; for (const b of this.storesNear(world, a, radius || 20)) { const dd = LW.dist(a.x, a.y, b.x, b.y); if (dd < bd) { bd = dd; best = b; } } return best; },
    /** Épület-adta szorzó a közelben (műhely, labor, egyetem…): a legjobb ilyen épület egy tulajdonságára. */
    buildingBonus(world, x, y, prop, radius) { let best = 0; for (const b of world.buildingsNear(x | 0, y | 0, radius || 12)) { if (b.progress < 1) continue; const v = B[b.kind][prop]; if (v && v > best) best = v; } return best; },
    /** A világ korszaka az élők tudásából. */
    techLevel(known) {
      const has = (k) => known.has(k);
      // korszak-mérföldkövek: az a kor számít, amelynek a kulcstechnológiája már ismert
      const ANCHORS = [['beyond', ['world_simulation']], ['ai', ['artificial_intelligence']], ['digital', ['computer']], ['modern', ['electrification', 'internal_combustion']], ['industrial', ['steam_engine', 'factory_system']], ['renaissance', ['printing', 'scientific_method']], ['medieval', ['universities', 'paper_making']], ['classical', ['architecture', 'mathematics', 'steel_making']], ['iron', ['iron_smelting']], ['bronze', ['bronze_alloy']], ['copper', ['copper_smelting']]];
      for (const [era, keys] of ANCHORS) if (keys.some(has)) return ERAS[ERA_INDEX[era]][1];
      if (has('stone_masonry') && has('seed_planting')) return 'Újkőkor';
      if (has('seed_planting') || (has('pottery') && has('hut_construction'))) return 'Korai újkőkor';
      if (has('stone_knapping') && has('fire_making')) return 'Kőkor';
      if (has('stone_knapping') || has('fire_making') || has('shelter_building')) return 'Korai kőkor';
      return 'Kezdetleges';
    },
    eraOf(id) { const d = D[id]; return d ? (ERA_INDEX[d.era] ?? 0) : 0; },
    /** Az ismeretlen jövő: a Világmag után évente egy új, generált lehetőség — a Teremtőnek sincs rá szava. */
    futureStep(world) {
      const known = LW.Tech.worldKnowledge(world); if (!known.has('world_simulation')) return;
      world.futureTechs = world.futureTechs || []; const last = world.futureTechs[world.futureTechs.length - 1];
      if (last && !known.has(last.id)) return; // előbb az utolsó ismeretlent kell megtalálni
      if (last && world.tick - last.born < LW.TIME.TICKS_PER_YEAR * 2) return;
      const rng = world.rng; const n = world.futureTechs.length + 1;
      const PRE = ['Kvantum', 'Bio', 'Nano', 'Neuro', 'Hiper', 'Foton', 'Gravi', 'Tér', 'Idő', 'Plazma', 'Kripto', 'Szinguláris', 'Ön', 'Meta', 'Exo'];
      const ROOT = ['hálózat', 'motor', 'kohó', 'elme', 'vető', 'híd', 'kapu', 'mag', 'szövet', 'térkép', 'óra', 'tükör', 'kert', 'kút', 'lánc', 'sejt', 'burok', 'nyelv'];
      const name = `${rng.pick(PRE)}${rng.pick(ROOT)}`; const fxKeys = ['discovery', 'craft', 'health', 'speed', 'farm', 'teach', 'warmth', 'food'];
      const fx = {}; for (const k of rng.shuffle(fxKeys.slice()).slice(0, rng.int(1, 3))) fx[k] = Math.round(rng.range(0.1, 0.4) * 100) / 100;
      const own = world.language.place().toLowerCase();
      const t = { id: `future_${n}`, name, era: 'beyond', prereq: [last ? last.id : 'world_simulation'], items: { chip: rng.int(10, 40), electric_part: rng.int(4, 16) }, nearby: rng.pick(['data_center', 'lab', 'simulation_core']), difficulty: 0.985 + rng.f() * 0.01, skill: rng.pick(['crafting', 'medicine', 'building']), minSkill: 0.9, minPop: 105 + n * 20, fx, wow: `Ismeretlen: ${name}`, desc: `Amit még senki nem látott. Ők úgy hívják: „${own}”. ${rng.pick(['Az anyag új rendje.', 'A gondolat új alakja.', 'Az idő másképp folyik körülötte.', 'A világ széle közelebb jött.', 'Senki nem tudja, mire jó — még.'])}`, born: world.tick };
      world.futureTechs.push(t); this.registerFuture([t]);
      world.events.emit('FutureTech', { tick: world.tick, name, id: t.id });
    },
    registerFuture(list) { for (const t of list) { if (D[t.id]) continue; D[t.id] = { ...t }; } },
  };
  LW.Tech.techLevel = (known) => Tree.techLevel(known);
  LW.Tech.fx = (world, a) => Tree.fx(world, a);
  LW.Tech.mult = (world, a, k) => Tree.mult(world, a, k);
  LW.Tech.bestTool = (a, slot) => Tree.bestTool(a, slot);
  LW.Tree = Tree;
})(globalThis.LW || (globalThis.LW = {}));
